
CREATE DATABASE KYC;

CREATE TABLE KYC_Customers (
Customer_ID VARCHAR(10),
Customer_Name VARCHAR(50),
Age INT,
State VARCHAR(50),
Document_Type VARCHAR(20),
Verification_Status VARCHAR(20),
Risk_Level VARCHAR(20),
Rejection_Reason VARCHAR(50),
Verification_Time_Minutes INT
);




INSERT INTO KYC_Customers (Customer_ID, Customer_Name, Age, State, Document_Type, Verification_Status, Risk_Level, Rejection_Reason, Verification_Time_Minutes) VALUES
('C0001', 'Sneha Kapoor', 55, 'Karnataka', 'Aadhaar', 'Approved', 'Medium', 'NA', 8),
('C0002', 'Amit Kumar', 24, 'Rajasthan', 'PAN', 'Rejected', 'Low', 'Missing Information', 27),
('C0003', 'Sneha Kapoor', 34, 'Gujarat', 'Aadhaar', 'Pending', 'Low', 'NA', 7),
('C0004', 'Rohit Jain', 28, 'Karnataka', 'Passport', 'Rejected', 'Medium', 'Name Mismatch', 19),
('C0005', 'Neha Gupta', 42, 'Rajasthan', 'Passport', 'Pending', 'Low', 'NA', 6),
('C0006', 'Arjun Verma', 25, 'Delhi', 'PAN', 'Rejected', 'Medium', 'Missing Information', 29),
('C0007', 'Rahul Sharma', 41, 'Haryana', 'PAN', 'Approved', 'Medium', 'NA', 5),
('C0008', 'Pooja Yadav', 56, 'Rajasthan', 'Passport', 'Pending', 'High', 'NA', 23),
('C0009', 'Rohit Jain', 23, 'Haryana', 'Aadhaar', 'Rejected', 'High', 'Invalid Address', 29),
('C0010', 'Pooja Yadav', 31, 'Delhi', 'PAN', 'Rejected', 'High', 'Name Mismatch', 22),
('C0011', 'Rohit Jain', 44, 'Gujarat', 'PAN', 'Pending', 'Low', 'NA', 25),
('C0012', 'Neha Gupta', 33, 'Gujarat', 'PAN', 'Rejected', 'High', 'Missing Information', 19),
('C0013', 'Priya Singh', 33, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 9),
('C0014', 'Pooja Yadav', 25, 'Punjab', 'Passport', 'Approved', 'Medium', 'NA', 8),
('C0015', 'Rohit Jain', 42, 'Rajasthan', 'Aadhaar', 'Pending', 'High', 'NA', 8),
('C0016', 'Neha Gupta', 41, 'Maharashtra', 'PAN', 'Approved', 'Low', 'NA', 8),
('C0017', 'Arjun Verma', 28, 'Karnataka', 'PAN', 'Approved', 'High', 'NA', 24),
('C0018', 'Arjun Verma', 21, 'Uttar Pradesh', 'Passport', 'Rejected', 'Medium', 'Blurred Image', 12),
('C0019', 'Amit Kumar', 60, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'Low', 'NA', 18),
('C0020', 'Priya Singh', 61, 'Rajasthan', 'Aadhaar', 'Pending', 'Medium', 'NA', 20),
('C0021', 'Rahul Sharma', 29, 'Haryana', 'PAN', 'Pending', 'Low', 'NA', 8),
('C0022', 'Rahul Sharma', 53, 'Punjab', 'PAN', 'Rejected', 'High', 'Name Mismatch', 5),
('C0023', 'Rahul Sharma', 51, 'Haryana', 'Passport', 'Approved', 'Medium', 'NA', 24),
('C0024', 'Priya Singh', 18, 'Uttar Pradesh', 'Passport', 'Approved', 'High', 'NA', 7),
('C0025', 'Rahul Sharma', 18, 'Delhi', 'Passport', 'Approved', 'Low', 'NA', 25),
('C0026', 'Pooja Yadav', 22, 'Rajasthan', 'PAN', 'Approved', 'Low', 'NA', 18),
('C0027', 'Rohit Jain', 41, 'Rajasthan', 'Passport', 'Approved', 'Low', 'NA', 28),
('C0028', 'Neha Gupta', 43, 'Rajasthan', 'Passport', 'Pending', 'Low', 'NA', 6),
('C0029', 'Arjun Verma', 41, 'Karnataka', 'PAN', 'Approved', 'High', 'NA', 13),
('C0030', 'Arjun Verma', 36, 'Haryana', 'PAN', 'Rejected', 'Low', 'Missing Information', 20),
('C0031', 'Amit Kumar', 50, 'Delhi', 'Passport', 'Approved', 'Medium', 'NA', 14),
('C0032', 'Rahul Sharma', 62, 'Maharashtra', 'PAN', 'Pending', 'High', 'NA', 5),
('C0033', 'Rahul Sharma', 43, 'Karnataka', 'Passport', 'Approved', 'Low', 'NA', 9),
('C0034', 'Neha Gupta', 42, 'Rajasthan', 'Passport', 'Approved', 'Low', 'NA', 7),
('C0035', 'Priya Singh', 40, 'Karnataka', 'Passport', 'Rejected', 'Low', 'Blurred Image', 16),
('C0036', 'Priya Singh', 58, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Name Mismatch', 24),
('C0037', 'Arjun Verma', 43, 'Gujarat', 'Aadhaar', 'Rejected', 'Low', 'Blurred Image', 15),
('C0038', 'Arjun Verma', 47, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 20),
('C0039', 'Neha Gupta', 45, 'Gujarat', 'PAN', 'Pending', 'High', 'NA', 17),
('C0040', 'Pooja Yadav', 25, 'Delhi', 'Aadhaar', 'Pending', 'Medium', 'NA', 25),
('C0041', 'Pooja Yadav', 62, 'Maharashtra', 'Passport', 'Rejected', 'Low', 'Missing Information', 7),
('C0042', 'Neha Gupta', 39, 'Karnataka', 'Passport', 'Rejected', 'Medium', 'Expired Document', 19),
('C0043', 'Priya Singh', 20, 'Rajasthan', 'Passport', 'Pending', 'Medium', 'NA', 24),
('C0044', 'Sneha Kapoor', 45, 'Rajasthan', 'Aadhaar', 'Pending', 'High', 'NA', 16),
('C0045', 'Neha Gupta', 33, 'Rajasthan', 'PAN', 'Pending', 'Low', 'NA', 23),
('C0046', 'Priya Singh', 47, 'Gujarat', 'PAN', 'Pending', 'Low', 'NA', 23),
('C0047', 'Arjun Verma', 28, 'Uttar Pradesh', 'Passport', 'Approved', 'Medium', 'NA', 12),
('C0048', 'Amit Kumar', 21, 'Punjab', 'PAN', 'Rejected', 'High', 'Missing Information', 14),
('C0049', 'Amit Kumar', 36, 'Haryana', 'PAN', 'Pending', 'High', 'NA', 27),
('C0050', 'Rahul Sharma', 55, 'Punjab', 'Passport', 'Pending', 'Medium', 'NA', 21),
('C0051', 'Rahul Sharma', 23, 'Punjab', 'Passport', 'Pending', 'High', 'NA', 11),
('C0052', 'Amit Kumar', 42, 'Karnataka', 'Aadhaar', 'Pending', 'Low', 'NA', 29),
('C0053', 'Sneha Kapoor', 22, 'Haryana', 'Passport', 'Rejected', 'High', 'Name Mismatch', 20),
('C0054', 'Sneha Kapoor', 20, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Medium', 'Expired Document', 20),
('C0055', 'Pooja Yadav', 41, 'Karnataka', 'Passport', 'Rejected', 'High', 'Invalid Address', 27),
('C0056', 'Priya Singh', 19, 'Haryana', 'Aadhaar', 'Rejected', 'Medium', 'Expired Document', 21),
('C0057', 'Rahul Sharma', 18, 'Haryana', 'Passport', 'Rejected', 'Low', 'Expired Document', 20),
('C0058', 'Neha Gupta', 19, 'Delhi', 'Passport', 'Approved', 'High', 'NA', 26),
('C0059', 'Neha Gupta', 35, 'Gujarat', 'PAN', 'Rejected', 'High', 'Missing Information', 21),
('C0060', 'Pooja Yadav', 48, 'Gujarat', 'PAN', 'Rejected', 'Medium', 'Name Mismatch', 18),
('C0061', 'Priya Singh', 59, 'Maharashtra', 'Passport', 'Rejected', 'Low', 'Blurred Image', 17),
('C0062', 'Amit Kumar', 59, 'Haryana', 'PAN', 'Rejected', 'Low', 'Expired Document', 5),
('C0063', 'Sneha Kapoor', 40, 'Maharashtra', 'Passport', 'Pending', 'Low', 'NA', 27),
('C0064', 'Rahul Sharma', 39, 'Haryana', 'Aadhaar', 'Approved', 'Medium', 'NA', 10),
('C0065', 'Pooja Yadav', 37, 'Gujarat', 'Aadhaar', 'Rejected', 'High', 'Missing Information', 29),
('C0066', 'Pooja Yadav', 62, 'Haryana', 'Aadhaar', 'Approved', 'High', 'NA', 5),
('C0067', 'Amit Kumar', 32, 'Punjab', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 15),
('C0068', 'Amit Kumar', 51, 'Karnataka', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 28),
('C0069', 'Arjun Verma', 21, 'Uttar Pradesh', 'PAN', 'Pending', 'High', 'NA', 5),
('C0070', 'Amit Kumar', 44, 'Punjab', 'Aadhaar', 'Pending', 'High', 'NA', 8),
('C0071', 'Neha Gupta', 31, 'Uttar Pradesh', 'PAN', 'Pending', 'Medium', 'NA', 9),
('C0072', 'Sneha Kapoor', 49, 'Maharashtra', 'Passport', 'Rejected', 'High', 'Name Mismatch', 9),
('C0073', 'Sneha Kapoor', 57, 'Haryana', 'Aadhaar', 'Rejected', 'Low', 'Expired Document', 18),
('C0074', 'Neha Gupta', 29, 'Punjab', 'Aadhaar', 'Approved', 'Medium', 'NA', 30),
('C0075', 'Arjun Verma', 36, 'Rajasthan', 'Passport', 'Pending', 'Medium', 'NA', 11),
('C0076', 'Priya Singh', 62, 'Punjab', 'Passport', 'Rejected', 'Medium', 'Blurred Image', 28),
('C0077', 'Rohit Jain', 62, 'Gujarat', 'Aadhaar', 'Pending', 'High', 'NA', 7),
('C0078', 'Sneha Kapoor', 57, 'Gujarat', 'Aadhaar', 'Approved', 'Low', 'NA', 29),
('C0079', 'Rohit Jain', 34, 'Punjab', 'Aadhaar', 'Rejected', 'Low', 'Name Mismatch', 11),
('C0080', 'Sneha Kapoor', 31, 'Haryana', 'PAN', 'Pending', 'Medium', 'NA', 19),
('C0081', 'Arjun Verma', 28, 'Karnataka', 'PAN', 'Pending', 'High', 'NA', 25),
('C0082', 'Priya Singh', 63, 'Delhi', 'PAN', 'Pending', 'High', 'NA', 15),
('C0083', 'Amit Kumar', 30, 'Maharashtra', 'Aadhaar', 'Rejected', 'Low', 'Name Mismatch', 18),
('C0084', 'Rahul Sharma', 39, 'Maharashtra', 'Aadhaar', 'Pending', 'Medium', 'NA', 19),
('C0085', 'Amit Kumar', 24, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 9),
('C0086', 'Amit Kumar', 47, 'Haryana', 'Aadhaar', 'Approved', 'High', 'NA', 12),
('C0087', 'Priya Singh', 35, 'Rajasthan', 'Passport', 'Pending', 'Medium', 'NA', 13),
('C0088', 'Neha Gupta', 28, 'Karnataka', 'PAN', 'Approved', 'Low', 'NA', 27),
('C0089', 'Amit Kumar', 23, 'Punjab', 'PAN', 'Approved', 'High', 'NA', 11),
('C0090', 'Neha Gupta', 31, 'Gujarat', 'Passport', 'Approved', 'Medium', 'NA', 26),
('C0091', 'Pooja Yadav', 22, 'Delhi', 'Aadhaar', 'Rejected', 'Low', 'Expired Document', 11),
('C0092', 'Rahul Sharma', 19, 'Rajasthan', 'PAN', 'Approved', 'Medium', 'NA', 6),
('C0093', 'Sneha Kapoor', 21, 'Haryana', 'PAN', 'Approved', 'Medium', 'NA', 29),
('C0094', 'Pooja Yadav', 35, 'Uttar Pradesh', 'PAN', 'Approved', 'Low', 'NA', 10),
('C0095', 'Neha Gupta', 44, 'Haryana', 'PAN', 'Rejected', 'Low', 'Invalid Address', 16),
('C0096', 'Pooja Yadav', 58, 'Haryana', 'Aadhaar', 'Pending', 'Low', 'NA', 8),
('C0097', 'Neha Gupta', 48, 'Punjab', 'PAN', 'Rejected', 'High', 'Invalid Address', 28),
('C0098', 'Arjun Verma', 64, 'Punjab', 'Passport', 'Approved', 'High', 'NA', 23),
('C0099', 'Rahul Sharma', 61, 'Maharashtra', 'Passport', 'Rejected', 'High', 'Name Mismatch', 11),
('C0100', 'Neha Gupta', 32, 'Karnataka', 'Aadhaar', 'Approved', 'Low', 'NA', 9);

INSERT INTO KYC_Customers (Customer_ID, Customer_Name, Age, State, Document_Type, Verification_Status, Risk_Level, Rejection_Reason, Verification_Time_Minutes) VALUES
('C0101', 'Sneha Kapoor', 30, 'Punjab', 'Passport', 'Rejected', 'Low', 'Expired Document', 16),
('C0102', 'Arjun Verma', 47, 'Karnataka', 'PAN', 'Pending', 'Medium', 'NA', 12),
('C0103', 'Amit Kumar', 21, 'Punjab', 'Aadhaar', 'Approved', 'High', 'NA', 22),
('C0104', 'Neha Gupta', 36, 'Gujarat', 'PAN', 'Rejected', 'Low', 'Expired Document', 24),
('C0105', 'Rohit Jain', 54, 'Punjab', 'PAN', 'Rejected', 'Medium', 'Expired Document', 27),
('C0106', 'Amit Kumar', 44, 'Rajasthan', 'Aadhaar', 'Pending', 'Medium', 'NA', 14),
('C0107', 'Sneha Kapoor', 56, 'Delhi', 'Passport', 'Approved', 'Low', 'NA', 15),
('C0108', 'Arjun Verma', 28, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Missing Information', 17),
('C0109', 'Rohit Jain', 18, 'Gujarat', 'Passport', 'Approved', 'Low', 'NA', 11),
('C0110', 'Neha Gupta', 33, 'Rajasthan', 'PAN', 'Approved', 'High', 'NA', 17),
('C0111', 'Pooja Yadav', 56, 'Gujarat', 'PAN', 'Rejected', 'Medium', 'Missing Information', 21),
('C0112', 'Arjun Verma', 23, 'Gujarat', 'Passport', 'Pending', 'High', 'NA', 10),
('C0113', 'Pooja Yadav', 37, 'Karnataka', 'PAN', 'Approved', 'Medium', 'NA', 20),
('C0114', 'Priya Singh', 24, 'Gujarat', 'PAN', 'Approved', 'Low', 'NA', 23),
('C0115', 'Arjun Verma', 64, 'Karnataka', 'Aadhaar', 'Rejected', 'High', 'Blurred Image', 23),
('C0116', 'Neha Gupta', 53, 'Karnataka', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 24),
('C0117', 'Rohit Jain', 43, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 27),
('C0118', 'Priya Singh', 53, 'Delhi', 'Passport', 'Approved', 'Low', 'NA', 12),
('C0119', 'Amit Kumar', 59, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'High', 'NA', 16),
('C0120', 'Priya Singh', 18, 'Uttar Pradesh', 'PAN', 'Pending', 'Low', 'NA', 10),
('C0121', 'Neha Gupta', 60, 'Uttar Pradesh', 'Passport', 'Rejected', 'High', 'Invalid Address', 11),
('C0122', 'Pooja Yadav', 61, 'Karnataka', 'Aadhaar', 'Rejected', 'High', 'Invalid Address', 14),
('C0123', 'Sneha Kapoor', 25, 'Rajasthan', 'Aadhaar', 'Rejected', 'Medium', 'Missing Information', 16),
('C0124', 'Sneha Kapoor', 60, 'Punjab', 'Passport', 'Pending', 'Medium', 'NA', 14),
('C0125', 'Sneha Kapoor', 36, 'Haryana', 'Passport', 'Approved', 'Low', 'NA', 30),
('C0126', 'Amit Kumar', 56, 'Rajasthan', 'Passport', 'Rejected', 'Low', 'Expired Document', 8),
('C0127', 'Arjun Verma', 59, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 19),
('C0128', 'Rohit Jain', 20, 'Rajasthan', 'Aadhaar', 'Rejected', 'Medium', 'Invalid Address', 12),
('C0129', 'Sneha Kapoor', 18, 'Rajasthan', 'Passport', 'Rejected', 'Low', 'Blurred Image', 15),
('C0130', 'Amit Kumar', 41, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'High', 'NA', 26),
('C0131', 'Sneha Kapoor', 27, 'Delhi', 'Aadhaar', 'Rejected', 'Medium', 'Expired Document', 10),
('C0132', 'Rohit Jain', 39, 'Delhi', 'Passport', 'Approved', 'High', 'NA', 16),
('C0133', 'Neha Gupta', 36, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Low', 'Missing Information', 13),
('C0134', 'Rohit Jain', 31, 'Delhi', 'Passport', 'Rejected', 'High', 'Invalid Address', 27),
('C0135', 'Neha Gupta', 43, 'Delhi', 'Passport', 'Rejected', 'High', 'Name Mismatch', 22),
('C0136', 'Sneha Kapoor', 34, 'Rajasthan', 'Aadhaar', 'Rejected', 'High', 'Missing Information', 6),
('C0137', 'Neha Gupta', 62, 'Delhi', 'Aadhaar', 'Pending', 'High', 'NA', 30),
('C0138', 'Arjun Verma', 65, 'Gujarat', 'Passport', 'Rejected', 'Medium', 'Missing Information', 17),
('C0139', 'Priya Singh', 24, 'Punjab', 'Passport', 'Rejected', 'Medium', 'Expired Document', 16),
('C0140', 'Sneha Kapoor', 35, 'Punjab', 'Passport', 'Pending', 'Low', 'NA', 7),
('C0141', 'Amit Kumar', 59, 'Maharashtra', 'Aadhaar', 'Pending', 'Low', 'NA', 10),
('C0142', 'Priya Singh', 64, 'Rajasthan', 'Passport', 'Approved', 'Low', 'NA', 6),
('C0143', 'Sneha Kapoor', 26, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 15),
('C0144', 'Rahul Sharma', 19, 'Gujarat', 'PAN', 'Approved', 'Low', 'NA', 25),
('C0145', 'Rahul Sharma', 40, 'Gujarat', 'Passport', 'Rejected', 'Low', 'Invalid Address', 30),
('C0146', 'Amit Kumar', 50, 'Haryana', 'PAN', 'Rejected', 'Low', 'Missing Information', 26),
('C0147', 'Amit Kumar', 30, 'Delhi', 'Passport', 'Pending', 'High', 'NA', 19),
('C0148', 'Sneha Kapoor', 52, 'Karnataka', 'PAN', 'Pending', 'Low', 'NA', 28),
('C0149', 'Sneha Kapoor', 49, 'Haryana', 'Aadhaar', 'Pending', 'Low', 'NA', 6),
('C0150', 'Sneha Kapoor', 28, 'Rajasthan', 'Passport', 'Approved', 'Low', 'NA', 21),
('C0151', 'Rahul Sharma', 43, 'Karnataka', 'Aadhaar', 'Approved', 'High', 'NA', 20),
('C0152', 'Amit Kumar', 57, 'Karnataka', 'Aadhaar', 'Approved', 'High', 'NA', 15),
('C0153', 'Rahul Sharma', 54, 'Haryana', 'PAN', 'Approved', 'Low', 'NA', 15),
('C0154', 'Rohit Jain', 42, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'High', 'NA', 8),
('C0155', 'Neha Gupta', 65, 'Delhi', 'Aadhaar', 'Rejected', 'Medium', 'Missing Information', 20),
('C0156', 'Arjun Verma', 23, 'Rajasthan', 'Passport', 'Rejected', 'Low', 'Expired Document', 20),
('C0157', 'Amit Kumar', 28, 'Maharashtra', 'PAN', 'Approved', 'Medium', 'NA', 19),
('C0158', 'Rahul Sharma', 33, 'Delhi', 'Passport', 'Approved', 'Low', 'NA', 21),
('C0159', 'Sneha Kapoor', 49, 'Uttar Pradesh', 'Passport', 'Rejected', 'High', 'Blurred Image', 15),
('C0160', 'Amit Kumar', 30, 'Punjab', 'PAN', 'Pending', 'High', 'NA', 22),
('C0161', 'Pooja Yadav', 55, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 12),
('C0162', 'Pooja Yadav', 65, 'Haryana', 'PAN', 'Approved', 'High', 'NA', 26),
('C0163', 'Neha Gupta', 54, 'Punjab', 'PAN', 'Pending', 'Medium', 'NA', 21),
('C0164', 'Amit Kumar', 61, 'Rajasthan', 'Passport', 'Pending', 'Low', 'NA', 17),
('C0165', 'Neha Gupta', 19, 'Maharashtra', 'Passport', 'Approved', 'Medium', 'NA', 12),
('C0166', 'Rahul Sharma', 54, 'Karnataka', 'Passport', 'Approved', 'High', 'NA', 29),
('C0167', 'Pooja Yadav', 28, 'Rajasthan', 'Aadhaar', 'Pending', 'Low', 'NA', 23),
('C0168', 'Sneha Kapoor', 56, 'Haryana', 'Aadhaar', 'Pending', 'Medium', 'NA', 6),
('C0169', 'Neha Gupta', 29, 'Gujarat', 'PAN', 'Approved', 'High', 'NA', 15),
('C0170', 'Arjun Verma', 42, 'Haryana', 'Aadhaar', 'Pending', 'High', 'NA', 23),
('C0171', 'Pooja Yadav', 21, 'Maharashtra', 'Passport', 'Rejected', 'High', 'Expired Document', 15),
('C0172', 'Rohit Jain', 49, 'Uttar Pradesh', 'Passport', 'Pending', 'Low', 'NA', 22),
('C0173', 'Arjun Verma', 54, 'Rajasthan', 'PAN', 'Approved', 'Medium', 'NA', 24),
('C0174', 'Rohit Jain', 43, 'Punjab', 'Passport', 'Pending', 'High', 'NA', 12),
('C0175', 'Amit Kumar', 43, 'Delhi', 'Aadhaar', 'Pending', 'High', 'NA', 7),
('C0176', 'Neha Gupta', 37, 'Karnataka', 'Passport', 'Approved', 'High', 'NA', 22),
('C0177', 'Amit Kumar', 18, 'Rajasthan', 'PAN', 'Approved', 'High', 'NA', 7),
('C0178', 'Rohit Jain', 38, 'Maharashtra', 'Passport', 'Rejected', 'Medium', 'Missing Information', 14),
('C0179', 'Rahul Sharma', 20, 'Uttar Pradesh', 'Passport', 'Rejected', 'Medium', 'Missing Information', 30),
('C0180', 'Arjun Verma', 56, 'Karnataka', 'Passport', 'Pending', 'Low', 'NA', 8),
('C0181', 'Sneha Kapoor', 32, 'Haryana', 'Passport', 'Rejected', 'Low', 'Invalid Address', 5),
('C0182', 'Rohit Jain', 47, 'Maharashtra', 'Aadhaar', 'Rejected', 'Low', 'Invalid Address', 28),
('C0183', 'Pooja Yadav', 55, 'Maharashtra', 'PAN', 'Rejected', 'Medium', 'Missing Information', 24),
('C0184', 'Priya Singh', 43, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 14),
('C0185', 'Rahul Sharma', 51, 'Delhi', 'Passport', 'Rejected', 'Low', 'Blurred Image', 21),
('C0186', 'Priya Singh', 47, 'Maharashtra', 'Passport', 'Rejected', 'High', 'Name Mismatch', 5),
('C0187', 'Pooja Yadav', 46, 'Karnataka', 'PAN', 'Approved', 'High', 'NA', 28),
('C0188', 'Arjun Verma', 39, 'Karnataka', 'Aadhaar', 'Pending', 'Low', 'NA', 27),
('C0189', 'Rahul Sharma', 51, 'Gujarat', 'PAN', 'Rejected', 'Medium', 'Expired Document', 30),
('C0190', 'Rohit Jain', 20, 'Delhi', 'Passport', 'Rejected', 'High', 'Expired Document', 22),
('C0191', 'Sneha Kapoor', 65, 'Punjab', 'Passport', 'Pending', 'High', 'NA', 27),
('C0192', 'Amit Kumar', 25, 'Punjab', 'PAN', 'Approved', 'High', 'NA', 12),
('C0193', 'Priya Singh', 19, 'Punjab', 'Passport', 'Approved', 'Low', 'NA', 10),
('C0194', 'Pooja Yadav', 59, 'Karnataka', 'Passport', 'Rejected', 'Medium', 'Blurred Image', 24),
('C0195', 'Rahul Sharma', 23, 'Haryana', 'Passport', 'Pending', 'High', 'NA', 19),
('C0196', 'Pooja Yadav', 46, 'Karnataka', 'PAN', 'Rejected', 'High', 'Blurred Image', 11),
('C0197', 'Arjun Verma', 52, 'Punjab', 'Aadhaar', 'Rejected', 'Medium', 'Expired Document', 15),
('C0198', 'Sneha Kapoor', 41, 'Maharashtra', 'PAN', 'Rejected', 'Medium', 'Expired Document', 25),
('C0199', 'Rahul Sharma', 39, 'Maharashtra', 'Aadhaar', 'Pending', 'High', 'NA', 10),
('C0200', 'Rohit Jain', 30, 'Gujarat', 'Passport', 'Rejected', 'Medium', 'Invalid Address', 5);

INSERT INTO KYC_Customers (Customer_ID, Customer_Name, Age, State, Document_Type, Verification_Status, Risk_Level, Rejection_Reason, Verification_Time_Minutes) VALUES
('C0201', 'Neha Gupta', 34, 'Uttar Pradesh', 'PAN', 'Approved', 'Low', 'NA', 14),
('C0202', 'Rohit Jain', 35, 'Punjab', 'Passport', 'Pending', 'Low', 'NA', 30),
('C0203', 'Rohit Jain', 32, 'Gujarat', 'Aadhaar', 'Rejected', 'High', 'Missing Information', 7),
('C0204', 'Amit Kumar', 63, 'Gujarat', 'PAN', 'Approved', 'High', 'NA', 7),
('C0205', 'Amit Kumar', 65, 'Gujarat', 'Aadhaar', 'Rejected', 'Medium', 'Blurred Image', 14),
('C0206', 'Pooja Yadav', 29, 'Karnataka', 'Passport', 'Pending', 'Low', 'NA', 14),
('C0207', 'Rahul Sharma', 24, 'Punjab', 'PAN', 'Pending', 'Low', 'NA', 6),
('C0208', 'Amit Kumar', 46, 'Delhi', 'PAN', 'Rejected', 'High', 'Name Mismatch', 25),
('C0209', 'Amit Kumar', 23, 'Gujarat', 'PAN', 'Pending', 'Low', 'NA', 28),
('C0210', 'Priya Singh', 46, 'Haryana', 'Aadhaar', 'Rejected', 'Low', 'Invalid Address', 11),
('C0211', 'Arjun Verma', 22, 'Delhi', 'Aadhaar', 'Pending', 'Low', 'NA', 21),
('C0212', 'Rohit Jain', 30, 'Karnataka', 'Aadhaar', 'Pending', 'High', 'NA', 5),
('C0213', 'Arjun Verma', 58, 'Haryana', 'PAN', 'Rejected', 'Medium', 'Missing Information', 13),
('C0214', 'Priya Singh', 32, 'Maharashtra', 'Passport', 'Pending', 'High', 'NA', 22),
('C0215', 'Priya Singh', 65, 'Karnataka', 'Passport', 'Rejected', 'High', 'Missing Information', 20),
('C0216', 'Sneha Kapoor', 29, 'Rajasthan', 'PAN', 'Rejected', 'Low', 'Expired Document', 21),
('C0217', 'Pooja Yadav', 52, 'Rajasthan', 'Passport', 'Approved', 'Low', 'NA', 23),
('C0218', 'Rohit Jain', 38, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Blurred Image', 17),
('C0219', 'Neha Gupta', 55, 'Rajasthan', 'PAN', 'Pending', 'High', 'NA', 29),
('C0220', 'Sneha Kapoor', 65, 'Karnataka', 'Aadhaar', 'Approved', 'Medium', 'NA', 12),
('C0221', 'Sneha Kapoor', 32, 'Rajasthan', 'Aadhaar', 'Rejected', 'Medium', 'Blurred Image', 19),
('C0222', 'Rahul Sharma', 33, 'Rajasthan', 'Aadhaar', 'Approved', 'High', 'NA', 7),
('C0223', 'Amit Kumar', 33, 'Haryana', 'PAN', 'Rejected', 'High', 'Expired Document', 27),
('C0224', 'Arjun Verma', 21, 'Maharashtra', 'Aadhaar', 'Pending', 'Low', 'NA', 13),
('C0225', 'Amit Kumar', 18, 'Haryana', 'PAN', 'Pending', 'Low', 'NA', 25),
('C0226', 'Sneha Kapoor', 28, 'Gujarat', 'Aadhaar', 'Rejected', 'Low', 'Blurred Image', 10),
('C0227', 'Neha Gupta', 28, 'Haryana', 'PAN', 'Rejected', 'High', 'Missing Information', 9),
('C0228', 'Amit Kumar', 48, 'Rajasthan', 'PAN', 'Rejected', 'Medium', 'Name Mismatch', 17),
('C0229', 'Pooja Yadav', 58, 'Delhi', 'Passport', 'Rejected', 'Low', 'Invalid Address', 16),
('C0230', 'Rohit Jain', 21, 'Gujarat', 'PAN', 'Rejected', 'Low', 'Name Mismatch', 19),
('C0231', 'Amit Kumar', 30, 'Delhi', 'Passport', 'Pending', 'Low', 'NA', 30),
('C0232', 'Priya Singh', 58, 'Maharashtra', 'Aadhaar', 'Pending', 'Low', 'NA', 15),
('C0233', 'Sneha Kapoor', 56, 'Punjab', 'Aadhaar', 'Pending', 'High', 'NA', 30),
('C0234', 'Rahul Sharma', 56, 'Haryana', 'Passport', 'Approved', 'Medium', 'NA', 12),
('C0235', 'Arjun Verma', 52, 'Haryana', 'PAN', 'Rejected', 'Low', 'Expired Document', 26),
('C0236', 'Rahul Sharma', 47, 'Gujarat', 'Passport', 'Pending', 'Low', 'NA', 30),
('C0237', 'Rohit Jain', 53, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'High', 'NA', 16),
('C0238', 'Priya Singh', 36, 'Uttar Pradesh', 'Passport', 'Approved', 'High', 'NA', 6),
('C0239', 'Neha Gupta', 55, 'Haryana', 'Aadhaar', 'Pending', 'Low', 'NA', 20),
('C0240', 'Sneha Kapoor', 49, 'Gujarat', 'Aadhaar', 'Rejected', 'High', 'Expired Document', 13),
('C0241', 'Amit Kumar', 32, 'Haryana', 'Aadhaar', 'Rejected', 'Low', 'Blurred Image', 13),
('C0242', 'Arjun Verma', 18, 'Gujarat', 'PAN', 'Rejected', 'Medium', 'Name Mismatch', 27),
('C0243', 'Pooja Yadav', 53, 'Gujarat', 'Aadhaar', 'Pending', 'High', 'NA', 27),
('C0244', 'Sneha Kapoor', 35, 'Gujarat', 'Aadhaar', 'Rejected', 'High', 'Name Mismatch', 24),
('C0245', 'Rohit Jain', 34, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 11),
('C0246', 'Neha Gupta', 26, 'Maharashtra', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 9),
('C0247', 'Neha Gupta', 50, 'Delhi', 'Passport', 'Rejected', 'High', 'Missing Information', 7),
('C0248', 'Neha Gupta', 54, 'Maharashtra', 'PAN', 'Rejected', 'Low', 'Missing Information', 15),
('C0249', 'Amit Kumar', 58, 'Delhi', 'Passport', 'Pending', 'High', 'NA', 30),
('C0250', 'Rohit Jain', 50, 'Delhi', 'Aadhaar', 'Approved', 'Low', 'NA', 13),
('C0251', 'Pooja Yadav', 44, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 24),
('C0252', 'Rohit Jain', 27, 'Maharashtra', 'Passport', 'Rejected', 'Low', 'Missing Information', 26),
('C0253', 'Neha Gupta', 22, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 20),
('C0254', 'Pooja Yadav', 41, 'Delhi', 'PAN', 'Pending', 'High', 'NA', 25),
('C0255', 'Rohit Jain', 27, 'Delhi', 'Passport', 'Approved', 'High', 'NA', 17),
('C0256', 'Priya Singh', 23, 'Rajasthan', 'Passport', 'Rejected', 'High', 'Expired Document', 5),
('C0257', 'Arjun Verma', 35, 'Karnataka', 'PAN', 'Approved', 'Low', 'NA', 15),
('C0258', 'Rohit Jain', 31, 'Karnataka', 'PAN', 'Pending', 'Low', 'NA', 15),
('C0259', 'Rahul Sharma', 37, 'Maharashtra', 'Aadhaar', 'Pending', 'Medium', 'NA', 11),
('C0260', 'Rahul Sharma', 44, 'Uttar Pradesh', 'PAN', 'Rejected', 'Medium', 'Name Mismatch', 10),
('C0261', 'Neha Gupta', 54, 'Gujarat', 'Passport', 'Approved', 'Medium', 'NA', 7),
('C0262', 'Sneha Kapoor', 52, 'Karnataka', 'PAN', 'Rejected', 'High', 'Name Mismatch', 24),
('C0263', 'Priya Singh', 65, 'Maharashtra', 'Passport', 'Pending', 'Low', 'NA', 14),
('C0264', 'Amit Kumar', 33, 'Punjab', 'Passport', 'Pending', 'Low', 'NA', 21),
('C0265', 'Priya Singh', 48, 'Punjab', 'PAN', 'Pending', 'Low', 'NA', 15),
('C0266', 'Sneha Kapoor', 42, 'Maharashtra', 'PAN', 'Approved', 'High', 'NA', 21),
('C0267', 'Rahul Sharma', 45, 'Karnataka', 'PAN', 'Approved', 'High', 'NA', 28),
('C0268', 'Pooja Yadav', 60, 'Punjab', 'PAN', 'Rejected', 'High', 'Invalid Address', 14),
('C0269', 'Rohit Jain', 31, 'Karnataka', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 26),
('C0270', 'Neha Gupta', 47, 'Gujarat', 'PAN', 'Approved', 'Medium', 'NA', 6),
('C0271', 'Rohit Jain', 26, 'Karnataka', 'Passport', 'Approved', 'High', 'NA', 24),
('C0272', 'Pooja Yadav', 48, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'High', 'NA', 18),
('C0273', 'Neha Gupta', 54, 'Punjab', 'PAN', 'Pending', 'Low', 'NA', 11),
('C0274', 'Amit Kumar', 19, 'Maharashtra', 'Aadhaar', 'Rejected', 'Medium', 'Expired Document', 6),
('C0275', 'Rohit Jain', 54, 'Karnataka', 'PAN', 'Pending', 'High', 'NA', 13),
('C0276', 'Amit Kumar', 43, 'Punjab', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 5),
('C0277', 'Amit Kumar', 50, 'Punjab', 'PAN', 'Pending', 'High', 'NA', 10),
('C0278', 'Priya Singh', 59, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 23),
('C0279', 'Arjun Verma', 31, 'Delhi', 'Passport', 'Approved', 'High', 'NA', 9),
('C0280', 'Neha Gupta', 24, 'Punjab', 'PAN', 'Approved', 'Low', 'NA', 30),
('C0281', 'Pooja Yadav', 39, 'Rajasthan', 'PAN', 'Pending', 'Low', 'NA', 9),
('C0282', 'Rohit Jain', 58, 'Karnataka', 'Passport', 'Approved', 'Low', 'NA', 10),
('C0283', 'Sneha Kapoor', 22, 'Gujarat', 'PAN', 'Pending', 'Low', 'NA', 27),
('C0284', 'Rohit Jain', 62, 'Karnataka', 'PAN', 'Rejected', 'Medium', 'Expired Document', 21),
('C0285', 'Rohit Jain', 27, 'Uttar Pradesh', 'PAN', 'Rejected', 'Medium', 'Missing Information', 12),
('C0286', 'Rahul Sharma', 21, 'Haryana', 'Passport', 'Approved', 'Low', 'NA', 26),
('C0287', 'Rohit Jain', 65, 'Punjab', 'Aadhaar', 'Rejected', 'High', 'Name Mismatch', 16),
('C0288', 'Sneha Kapoor', 36, 'Haryana', 'Passport', 'Pending', 'Medium', 'NA', 6),
('C0289', 'Sneha Kapoor', 65, 'Haryana', 'Passport', 'Pending', 'Low', 'NA', 12),
('C0290', 'Amit Kumar', 32, 'Haryana', 'PAN', 'Pending', 'Low', 'NA', 23),
('C0291', 'Rahul Sharma', 38, 'Punjab', 'PAN', 'Rejected', 'High', 'Name Mismatch', 16),
('C0292', 'Priya Singh', 26, 'Uttar Pradesh', 'PAN', 'Approved', 'High', 'NA', 23),
('C0293', 'Amit Kumar', 29, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 16),
('C0294', 'Rahul Sharma', 50, 'Haryana', 'Passport', 'Rejected', 'Medium', 'Missing Information', 6),
('C0295', 'Priya Singh', 29, 'Karnataka', 'Aadhaar', 'Approved', 'High', 'NA', 15),
('C0296', 'Rahul Sharma', 57, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Low', 'Expired Document', 25),
('C0297', 'Amit Kumar', 36, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 9),
('C0298', 'Rahul Sharma', 46, 'Maharashtra', 'PAN', 'Approved', 'High', 'NA', 6),
('C0299', 'Rahul Sharma', 32, 'Haryana', 'Passport', 'Rejected', 'High', 'Name Mismatch', 7),
('C0300', 'Amit Kumar', 31, 'Uttar Pradesh', 'Passport', 'Rejected', 'High', 'Missing Information', 5);

INSERT INTO KYC_Customers (Customer_ID, Customer_Name, Age, State, Document_Type, Verification_Status, Risk_Level, Rejection_Reason, Verification_Time_Minutes) VALUES
('C0301', 'Arjun Verma', 47, 'Karnataka', 'Aadhaar', 'Rejected', 'Medium', 'Invalid Address', 19),
('C0302', 'Amit Kumar', 48, 'Maharashtra', 'Aadhaar', 'Approved', 'Medium', 'NA', 21),
('C0303', 'Arjun Verma', 64, 'Gujarat', 'Aadhaar', 'Rejected', 'High', 'Blurred Image', 6),
('C0304', 'Amit Kumar', 31, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Missing Information', 12),
('C0305', 'Pooja Yadav', 60, 'Maharashtra', 'Passport', 'Pending', 'Medium', 'NA', 11),
('C0306', 'Amit Kumar', 47, 'Punjab', 'Aadhaar', 'Pending', 'Low', 'NA', 8),
('C0307', 'Rahul Sharma', 57, 'Delhi', 'PAN', 'Pending', 'Low', 'NA', 14),
('C0308', 'Neha Gupta', 33, 'Gujarat', 'PAN', 'Pending', 'High', 'NA', 11),
('C0309', 'Rohit Jain', 25, 'Punjab', 'PAN', 'Rejected', 'Medium', 'Expired Document', 22),
('C0310', 'Rohit Jain', 41, 'Rajasthan', 'Aadhaar', 'Rejected', 'Medium', 'Invalid Address', 12),
('C0311', 'Rohit Jain', 62, 'Gujarat', 'Passport', 'Approved', 'Low', 'NA', 28),
('C0312', 'Neha Gupta', 33, 'Karnataka', 'Aadhaar', 'Approved', 'High', 'NA', 11),
('C0313', 'Arjun Verma', 57, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Medium', 'Expired Document', 29),
('C0314', 'Amit Kumar', 49, 'Uttar Pradesh', 'PAN', 'Approved', 'Medium', 'NA', 20),
('C0315', 'Amit Kumar', 41, 'Rajasthan', 'Passport', 'Approved', 'Medium', 'NA', 23),
('C0316', 'Rahul Sharma', 44, 'Delhi', 'Aadhaar', 'Rejected', 'Low', 'Missing Information', 8),
('C0317', 'Rohit Jain', 64, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 25),
('C0318', 'Arjun Verma', 39, 'Rajasthan', 'PAN', 'Rejected', 'Medium', 'Expired Document', 6),
('C0319', 'Amit Kumar', 62, 'Maharashtra', 'PAN', 'Pending', 'Medium', 'NA', 29),
('C0320', 'Arjun Verma', 49, 'Karnataka', 'Passport', 'Approved', 'High', 'NA', 5),
('C0321', 'Rahul Sharma', 52, 'Delhi', 'Passport', 'Rejected', 'High', 'Name Mismatch', 11),
('C0322', 'Priya Singh', 42, 'Gujarat', 'Aadhaar', 'Rejected', 'Low', 'Name Mismatch', 12),
('C0323', 'Neha Gupta', 19, 'Maharashtra', 'Passport', 'Pending', 'High', 'NA', 19),
('C0324', 'Rohit Jain', 29, 'Maharashtra', 'Passport', 'Rejected', 'High', 'Missing Information', 5),
('C0325', 'Pooja Yadav', 44, 'Karnataka', 'Aadhaar', 'Pending', 'Low', 'NA', 24),
('C0326', 'Amit Kumar', 37, 'Rajasthan', 'PAN', 'Pending', 'Low', 'NA', 10),
('C0327', 'Neha Gupta', 20, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 12),
('C0328', 'Rohit Jain', 32, 'Karnataka', 'PAN', 'Pending', 'High', 'NA', 14),
('C0329', 'Rohit Jain', 32, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Low', 'NA', 27),
('C0330', 'Sneha Kapoor', 65, 'Punjab', 'Aadhaar', 'Approved', 'Medium', 'NA', 17),
('C0331', 'Sneha Kapoor', 37, 'Maharashtra', 'PAN', 'Rejected', 'Low', 'Name Mismatch', 9),
('C0332', 'Sneha Kapoor', 34, 'Punjab', 'Aadhaar', 'Pending', 'High', 'NA', 7),
('C0333', 'Rohit Jain', 65, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 7),
('C0334', 'Rahul Sharma', 41, 'Uttar Pradesh', 'PAN', 'Approved', 'High', 'NA', 6),
('C0335', 'Rahul Sharma', 29, 'Rajasthan', 'Aadhaar', 'Rejected', 'Low', 'Name Mismatch', 9),
('C0336', 'Amit Kumar', 57, 'Haryana', 'Passport', 'Rejected', 'Low', 'Invalid Address', 6),
('C0337', 'Neha Gupta', 25, 'Haryana', 'Aadhaar', 'Pending', 'High', 'NA', 25),
('C0338', 'Pooja Yadav', 56, 'Rajasthan', 'PAN', 'Approved', 'High', 'NA', 14),
('C0339', 'Arjun Verma', 36, 'Haryana', 'Passport', 'Approved', 'Low', 'NA', 9),
('C0340', 'Priya Singh', 62, 'Uttar Pradesh', 'Passport', 'Approved', 'Low', 'NA', 6),
('C0341', 'Sneha Kapoor', 19, 'Gujarat', 'PAN', 'Approved', 'High', 'NA', 10),
('C0342', 'Rahul Sharma', 38, 'Gujarat', 'PAN', 'Approved', 'High', 'NA', 15),
('C0343', 'Pooja Yadav', 32, 'Delhi', 'Passport', 'Pending', 'Medium', 'NA', 28),
('C0344', 'Rahul Sharma', 30, 'Gujarat', 'Aadhaar', 'Pending', 'High', 'NA', 20),
('C0345', 'Neha Gupta', 37, 'Gujarat', 'Passport', 'Approved', 'Low', 'NA', 11),
('C0346', 'Pooja Yadav', 60, 'Punjab', 'Aadhaar', 'Approved', 'Medium', 'NA', 22),
('C0347', 'Rohit Jain', 31, 'Uttar Pradesh', 'PAN', 'Pending', 'High', 'NA', 25),
('C0348', 'Rahul Sharma', 23, 'Haryana', 'Passport', 'Rejected', 'High', 'Name Mismatch', 11),
('C0349', 'Priya Singh', 28, 'Karnataka', 'Passport', 'Approved', 'High', 'NA', 13),
('C0350', 'Arjun Verma', 21, 'Gujarat', 'PAN', 'Pending', 'Low', 'NA', 17),
('C0351', 'Amit Kumar', 22, 'Delhi', 'Passport', 'Pending', 'High', 'NA', 27),
('C0352', 'Priya Singh', 54, 'Uttar Pradesh', 'PAN', 'Approved', 'High', 'NA', 6),
('C0353', 'Amit Kumar', 27, 'Uttar Pradesh', 'PAN', 'Approved', 'High', 'NA', 9),
('C0354', 'Rahul Sharma', 23, 'Gujarat', 'Passport', 'Pending', 'High', 'NA', 29),
('C0355', 'Rahul Sharma', 65, 'Karnataka', 'Passport', 'Rejected', 'High', 'Expired Document', 5),
('C0356', 'Sneha Kapoor', 21, 'Maharashtra', 'Aadhaar', 'Approved', 'High', 'NA', 27),
('C0357', 'Pooja Yadav', 26, 'Punjab', 'Passport', 'Rejected', 'Low', 'Invalid Address', 6),
('C0358', 'Amit Kumar', 36, 'Uttar Pradesh', 'PAN', 'Pending', 'Medium', 'NA', 15),
('C0359', 'Arjun Verma', 48, 'Delhi', 'Passport', 'Pending', 'High', 'NA', 5),
('C0360', 'Amit Kumar', 36, 'Delhi', 'PAN', 'Pending', 'High', 'NA', 9),
('C0361', 'Sneha Kapoor', 35, 'Gujarat', 'PAN', 'Pending', 'Medium', 'NA', 16),
('C0362', 'Pooja Yadav', 19, 'Punjab', 'Passport', 'Rejected', 'High', 'Invalid Address', 21),
('C0363', 'Pooja Yadav', 32, 'Punjab', 'Passport', 'Rejected', 'Low', 'Expired Document', 30),
('C0364', 'Amit Kumar', 28, 'Punjab', 'Passport', 'Pending', 'Medium', 'NA', 27),
('C0365', 'Neha Gupta', 53, 'Gujarat', 'Passport', 'Approved', 'High', 'NA', 29),
('C0366', 'Pooja Yadav', 34, 'Gujarat', 'Aadhaar', 'Approved', 'Low', 'NA', 7),
('C0367', 'Rahul Sharma', 61, 'Haryana', 'Aadhaar', 'Pending', 'Medium', 'NA', 9),
('C0368', 'Rahul Sharma', 53, 'Delhi', 'PAN', 'Approved', 'Medium', 'NA', 8),
('C0369', 'Pooja Yadav', 28, 'Maharashtra', 'Passport', 'Pending', 'Medium', 'NA', 19),
('C0370', 'Arjun Verma', 19, 'Uttar Pradesh', 'Passport', 'Rejected', 'High', 'Missing Information', 14),
('C0371', 'Sneha Kapoor', 63, 'Punjab', 'Passport', 'Approved', 'Low', 'NA', 24),
('C0372', 'Arjun Verma', 19, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 10),
('C0373', 'Arjun Verma', 32, 'Maharashtra', 'Passport', 'Approved', 'Medium', 'NA', 22),
('C0374', 'Sneha Kapoor', 21, 'Karnataka', 'Passport', 'Pending', 'Medium', 'NA', 16),
('C0375', 'Amit Kumar', 35, 'Haryana', 'Passport', 'Rejected', 'Medium', 'Expired Document', 5),
('C0376', 'Neha Gupta', 42, 'Gujarat', 'Aadhaar', 'Approved', 'Medium', 'NA', 12),
('C0377', 'Pooja Yadav', 31, 'Punjab', 'PAN', 'Approved', 'High', 'NA', 21),
('C0378', 'Neha Gupta', 29, 'Punjab', 'Aadhaar', 'Approved', 'Medium', 'NA', 7),
('C0379', 'Rahul Sharma', 28, 'Gujarat', 'Passport', 'Pending', 'High', 'NA', 22),
('C0380', 'Rohit Jain', 57, 'Punjab', 'Passport', 'Rejected', 'High', 'Expired Document', 17),
('C0381', 'Amit Kumar', 63, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Low', 'NA', 8),
('C0382', 'Neha Gupta', 47, 'Haryana', 'PAN', 'Pending', 'Medium', 'NA', 22),
('C0383', 'Priya Singh', 21, 'Gujarat', 'Passport', 'Pending', 'Low', 'NA', 11),
('C0384', 'Amit Kumar', 61, 'Punjab', 'PAN', 'Approved', 'High', 'NA', 8),
('C0385', 'Neha Gupta', 51, 'Delhi', 'Passport', 'Pending', 'High', 'NA', 5),
('C0386', 'Rohit Jain', 43, 'Maharashtra', 'Passport', 'Rejected', 'High', 'Blurred Image', 20),
('C0387', 'Sneha Kapoor', 61, 'Uttar Pradesh', 'Passport', 'Rejected', 'High', 'Missing Information', 26),
('C0388', 'Rohit Jain', 21, 'Delhi', 'PAN', 'Rejected', 'Medium', 'Expired Document', 16),
('C0389', 'Rohit Jain', 60, 'Punjab', 'PAN', 'Approved', 'Medium', 'NA', 25),
('C0390', 'Neha Gupta', 47, 'Karnataka', 'PAN', 'Rejected', 'Medium', 'Missing Information', 10),
('C0391', 'Arjun Verma', 65, 'Punjab', 'Aadhaar', 'Rejected', 'Medium', 'Invalid Address', 22),
('C0392', 'Priya Singh', 33, 'Delhi', 'Passport', 'Approved', 'Medium', 'NA', 16),
('C0393', 'Neha Gupta', 61, 'Haryana', 'Aadhaar', 'Approved', 'Low', 'NA', 17),
('C0394', 'Rohit Jain', 48, 'Karnataka', 'PAN', 'Rejected', 'Low', 'Missing Information', 9),
('C0395', 'Neha Gupta', 21, 'Maharashtra', 'Passport', 'Pending', 'Low', 'NA', 19),
('C0396', 'Neha Gupta', 44, 'Punjab', 'Aadhaar', 'Approved', 'Low', 'NA', 6),
('C0397', 'Priya Singh', 40, 'Haryana', 'Aadhaar', 'Rejected', 'High', 'Blurred Image', 16),
('C0398', 'Arjun Verma', 30, 'Karnataka', 'Passport', 'Pending', 'Medium', 'NA', 9),
('C0399', 'Arjun Verma', 46, 'Delhi', 'PAN', 'Rejected', 'Medium', 'Expired Document', 10),
('C0400', 'Sneha Kapoor', 37, 'Gujarat', 'Passport', 'Pending', 'Medium', 'NA', 17);

INSERT INTO KYC_Customers (Customer_ID, Customer_Name, Age, State, Document_Type, Verification_Status, Risk_Level, Rejection_Reason, Verification_Time_Minutes) VALUES
('C0401', 'Sneha Kapoor', 25, 'Maharashtra', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 17),
('C0402', 'Neha Gupta', 43, 'Punjab', 'Passport', 'Rejected', 'Low', 'Name Mismatch', 19),
('C0403', 'Arjun Verma', 34, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'High', 'NA', 11),
('C0404', 'Sneha Kapoor', 46, 'Maharashtra', 'Aadhaar', 'Approved', 'Low', 'NA', 25),
('C0405', 'Sneha Kapoor', 40, 'Rajasthan', 'Aadhaar', 'Approved', 'Low', 'NA', 10),
('C0406', 'Neha Gupta', 44, 'Karnataka', 'Aadhaar', 'Approved', 'Medium', 'NA', 25),
('C0407', 'Priya Singh', 61, 'Maharashtra', 'Passport', 'Rejected', 'Medium', 'Invalid Address', 15),
('C0408', 'Rahul Sharma', 57, 'Punjab', 'PAN', 'Approved', 'Medium', 'NA', 28),
('C0409', 'Arjun Verma', 25, 'Haryana', 'Passport', 'Rejected', 'Medium', 'Expired Document', 23),
('C0410', 'Pooja Yadav', 61, 'Haryana', 'Passport', 'Approved', 'High', 'NA', 29),
('C0411', 'Arjun Verma', 55, 'Haryana', 'Aadhaar', 'Rejected', 'Low', 'Blurred Image', 7),
('C0412', 'Arjun Verma', 53, 'Haryana', 'Passport', 'Approved', 'High', 'NA', 28),
('C0413', 'Rohit Jain', 18, 'Uttar Pradesh', 'Passport', 'Rejected', 'Medium', 'Missing Information', 15),
('C0414', 'Neha Gupta', 38, 'Maharashtra', 'Aadhaar', 'Approved', 'High', 'NA', 20),
('C0415', 'Sneha Kapoor', 33, 'Karnataka', 'Aadhaar', 'Approved', 'High', 'NA', 16),
('C0416', 'Rohit Jain', 58, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 30),
('C0417', 'Neha Gupta', 33, 'Rajasthan', 'PAN', 'Approved', 'Medium', 'NA', 13),
('C0418', 'Rahul Sharma', 46, 'Gujarat', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 22),
('C0419', 'Pooja Yadav', 53, 'Rajasthan', 'Passport', 'Rejected', 'High', 'Expired Document', 5),
('C0420', 'Rohit Jain', 25, 'Punjab', 'Passport', 'Approved', 'Low', 'NA', 18),
('C0421', 'Priya Singh', 56, 'Maharashtra', 'PAN', 'Pending', 'Medium', 'NA', 24),
('C0422', 'Amit Kumar', 45, 'Delhi', 'PAN', 'Approved', 'Low', 'NA', 8),
('C0423', 'Rahul Sharma', 47, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Missing Information', 30),
('C0424', 'Priya Singh', 60, 'Rajasthan', 'Passport', 'Rejected', 'High', 'Name Mismatch', 28),
('C0425', 'Amit Kumar', 32, 'Gujarat', 'PAN', 'Pending', 'Medium', 'NA', 5),
('C0426', 'Sneha Kapoor', 34, 'Gujarat', 'PAN', 'Approved', 'Medium', 'NA', 24),
('C0427', 'Neha Gupta', 64, 'Karnataka', 'PAN', 'Approved', 'Low', 'NA', 23),
('C0428', 'Sneha Kapoor', 18, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 7),
('C0429', 'Pooja Yadav', 24, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 21),
('C0430', 'Amit Kumar', 61, 'Delhi', 'Aadhaar', 'Rejected', 'Low', 'Expired Document', 16),
('C0431', 'Amit Kumar', 56, 'Gujarat', 'PAN', 'Approved', 'High', 'NA', 28),
('C0432', 'Neha Gupta', 29, 'Karnataka', 'PAN', 'Rejected', 'Medium', 'Name Mismatch', 9),
('C0433', 'Amit Kumar', 21, 'Karnataka', 'Aadhaar', 'Rejected', 'Low', 'Missing Information', 23),
('C0434', 'Priya Singh', 38, 'Delhi', 'PAN', 'Approved', 'High', 'NA', 29),
('C0435', 'Sneha Kapoor', 39, 'Haryana', 'Passport', 'Rejected', 'Medium', 'Expired Document', 27),
('C0436', 'Sneha Kapoor', 24, 'Delhi', 'Passport', 'Pending', 'Medium', 'NA', 17),
('C0437', 'Rohit Jain', 53, 'Karnataka', 'Aadhaar', 'Pending', 'Medium', 'NA', 11),
('C0438', 'Rahul Sharma', 26, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 10),
('C0439', 'Pooja Yadav', 37, 'Haryana', 'Passport', 'Pending', 'High', 'NA', 16),
('C0440', 'Priya Singh', 24, 'Haryana', 'Passport', 'Approved', 'Low', 'NA', 5),
('C0441', 'Sneha Kapoor', 19, 'Rajasthan', 'Aadhaar', 'Pending', 'High', 'NA', 7),
('C0442', 'Arjun Verma', 24, 'Rajasthan', 'PAN', 'Rejected', 'High', 'Invalid Address', 7),
('C0443', 'Neha Gupta', 43, 'Punjab', 'PAN', 'Pending', 'Medium', 'NA', 11),
('C0444', 'Sneha Kapoor', 33, 'Rajasthan', 'PAN', 'Rejected', 'High', 'Invalid Address', 7),
('C0445', 'Pooja Yadav', 36, 'Delhi', 'Aadhaar', 'Approved', 'Low', 'NA', 13),
('C0446', 'Rahul Sharma', 31, 'Rajasthan', 'Aadhaar', 'Pending', 'High', 'NA', 11),
('C0447', 'Pooja Yadav', 60, 'Delhi', 'Passport', 'Approved', 'Medium', 'NA', 25),
('C0448', 'Pooja Yadav', 29, 'Uttar Pradesh', 'PAN', 'Approved', 'Low', 'NA', 21),
('C0449', 'Rohit Jain', 60, 'Karnataka', 'PAN', 'Pending', 'Low', 'NA', 16),
('C0450', 'Priya Singh', 56, 'Gujarat', 'Aadhaar', 'Pending', 'High', 'NA', 21),
('C0451', 'Sneha Kapoor', 36, 'Gujarat', 'Aadhaar', 'Pending', 'Medium', 'NA', 17),
('C0452', 'Sneha Kapoor', 26, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'High', 'NA', 7),
('C0453', 'Rahul Sharma', 31, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 10),
('C0454', 'Sneha Kapoor', 37, 'Haryana', 'Aadhaar', 'Approved', 'Medium', 'NA', 15),
('C0455', 'Sneha Kapoor', 37, 'Punjab', 'Aadhaar', 'Rejected', 'Medium', 'Blurred Image', 8),
('C0456', 'Arjun Verma', 36, 'Delhi', 'Passport', 'Approved', 'Medium', 'NA', 13),
('C0457', 'Pooja Yadav', 45, 'Punjab', 'Aadhaar', 'Rejected', 'High', 'Invalid Address', 24),
('C0458', 'Rahul Sharma', 21, 'Punjab', 'Aadhaar', 'Approved', 'Low', 'NA', 13),
('C0459', 'Sneha Kapoor', 23, 'Rajasthan', 'PAN', 'Approved', 'Medium', 'NA', 16),
('C0460', 'Neha Gupta', 31, 'Delhi', 'Passport', 'Approved', 'Low', 'NA', 7),
('C0461', 'Pooja Yadav', 41, 'Delhi', 'Passport', 'Approved', 'Low', 'NA', 14),
('C0462', 'Priya Singh', 29, 'Punjab', 'PAN', 'Rejected', 'Medium', 'Name Mismatch', 17),
('C0463', 'Priya Singh', 49, 'Rajasthan', 'Passport', 'Approved', 'Low', 'NA', 9),
('C0464', 'Rohit Jain', 21, 'Delhi', 'PAN', 'Pending', 'Low', 'NA', 24),
('C0465', 'Sneha Kapoor', 41, 'Maharashtra', 'Passport', 'Pending', 'Low', 'NA', 11),
('C0466', 'Rahul Sharma', 19, 'Rajasthan', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 23),
('C0467', 'Neha Gupta', 39, 'Maharashtra', 'Aadhaar', 'Pending', 'Medium', 'NA', 17),
('C0468', 'Sneha Kapoor', 34, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 22),
('C0469', 'Arjun Verma', 61, 'Punjab', 'Passport', 'Rejected', 'High', 'Invalid Address', 21),
('C0470', 'Amit Kumar', 44, 'Rajasthan', 'Aadhaar', 'Rejected', 'Medium', 'Blurred Image', 29),
('C0471', 'Priya Singh', 48, 'Delhi', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 9),
('C0472', 'Priya Singh', 51, 'Rajasthan', 'Passport', 'Approved', 'High', 'NA', 24),
('C0473', 'Rahul Sharma', 31, 'Delhi', 'PAN', 'Pending', 'High', 'NA', 15),
('C0474', 'Pooja Yadav', 35, 'Punjab', 'Passport', 'Approved', 'High', 'NA', 28),
('C0475', 'Pooja Yadav', 51, 'Punjab', 'Passport', 'Approved', 'High', 'NA', 21),
('C0476', 'Rahul Sharma', 53, 'Haryana', 'Passport', 'Pending', 'Low', 'NA', 30),
('C0477', 'Arjun Verma', 60, 'Maharashtra', 'Aadhaar', 'Rejected', 'High', 'Missing Information', 16),
('C0478', 'Rahul Sharma', 25, 'Karnataka', 'Aadhaar', 'Rejected', 'Medium', 'Expired Document', 17),
('C0479', 'Neha Gupta', 41, 'Uttar Pradesh', 'Passport', 'Rejected', 'High', 'Missing Information', 13),
('C0480', 'Arjun Verma', 58, 'Gujarat', 'PAN', 'Approved', 'Medium', 'NA', 6),
('C0481', 'Amit Kumar', 47, 'Uttar Pradesh', 'Passport', 'Rejected', 'High', 'Missing Information', 15),
('C0482', 'Arjun Verma', 52, 'Punjab', 'Passport', 'Rejected', 'Medium', 'Expired Document', 29),
('C0483', 'Rohit Jain', 18, 'Karnataka', 'PAN', 'Pending', 'Medium', 'NA', 6),
('C0484', 'Amit Kumar', 37, 'Punjab', 'Passport', 'Approved', 'Low', 'NA', 10),
('C0485', 'Arjun Verma', 28, 'Maharashtra', 'PAN', 'Approved', 'Medium', 'NA', 17),
('C0486', 'Sneha Kapoor', 48, 'Punjab', 'Passport', 'Rejected', 'Low', 'Expired Document', 17),
('C0487', 'Rahul Sharma', 28, 'Delhi', 'PAN', 'Rejected', 'High', 'Blurred Image', 17),
('C0488', 'Arjun Verma', 50, 'Delhi', 'Passport', 'Rejected', 'Low', 'Invalid Address', 13),
('C0489', 'Rohit Jain', 31, 'Punjab', 'Aadhaar', 'Approved', 'High', 'NA', 21),
('C0490', 'Pooja Yadav', 37, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 14),
('C0491', 'Neha Gupta', 29, 'Delhi', 'Aadhaar', 'Approved', 'Low', 'NA', 24),
('C0492', 'Neha Gupta', 34, 'Rajasthan', 'Passport', 'Approved', 'Medium', 'NA', 21),
('C0493', 'Rahul Sharma', 28, 'Punjab', 'Aadhaar', 'Rejected', 'Low', 'Name Mismatch', 30),
('C0494', 'Rahul Sharma', 24, 'Punjab', 'Passport', 'Rejected', 'Medium', 'Expired Document', 26),
('C0495', 'Rohit Jain', 55, 'Karnataka', 'PAN', 'Pending', 'Medium', 'NA', 26),
('C0496', 'Sneha Kapoor', 34, 'Uttar Pradesh', 'PAN', 'Approved', 'High', 'NA', 22),
('C0497', 'Amit Kumar', 58, 'Karnataka', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 24),
('C0498', 'Priya Singh', 50, 'Uttar Pradesh', 'Passport', 'Approved', 'Low', 'NA', 26),
('C0499', 'Sneha Kapoor', 27, 'Delhi', 'Passport', 'Pending', 'Low', 'NA', 13),
('C0500', 'Arjun Verma', 56, 'Maharashtra', 'PAN', 'Rejected', 'Medium', 'Missing Information', 12);

INSERT INTO KYC_Customers (Customer_ID, Customer_Name, Age, State, Document_Type, Verification_Status, Risk_Level, Rejection_Reason, Verification_Time_Minutes) VALUES
('C0501', 'Priya Singh', 41, 'Delhi', 'Aadhaar', 'Rejected', 'High', 'Invalid Address', 27),
('C0502', 'Pooja Yadav', 35, 'Haryana', 'Passport', 'Pending', 'Low', 'NA', 22),
('C0503', 'Sneha Kapoor', 21, 'Punjab', 'Aadhaar', 'Rejected', 'Low', 'Blurred Image', 13),
('C0504', 'Sneha Kapoor', 28, 'Maharashtra', 'Aadhaar', 'Pending', 'Low', 'NA', 10),
('C0505', 'Arjun Verma', 36, 'Haryana', 'PAN', 'Rejected', 'Medium', 'Missing Information', 15),
('C0506', 'Neha Gupta', 24, 'Delhi', 'Aadhaar', 'Approved', 'High', 'NA', 29),
('C0507', 'Sneha Kapoor', 27, 'Haryana', 'PAN', 'Rejected', 'Medium', 'Name Mismatch', 22),
('C0508', 'Rahul Sharma', 26, 'Punjab', 'Passport', 'Rejected', 'High', 'Name Mismatch', 18),
('C0509', 'Neha Gupta', 36, 'Haryana', 'Passport', 'Pending', 'High', 'NA', 10),
('C0510', 'Arjun Verma', 50, 'Delhi', 'PAN', 'Approved', 'Low', 'NA', 26),
('C0511', 'Sneha Kapoor', 31, 'Rajasthan', 'PAN', 'Pending', 'Medium', 'NA', 20),
('C0512', 'Rohit Jain', 41, 'Gujarat', 'Aadhaar', 'Pending', 'High', 'NA', 26),
('C0513', 'Rahul Sharma', 52, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'High', 'NA', 16),
('C0514', 'Arjun Verma', 53, 'Gujarat', 'Passport', 'Rejected', 'Low', 'Invalid Address', 16),
('C0515', 'Sneha Kapoor', 43, 'Rajasthan', 'PAN', 'Rejected', 'Low', 'Expired Document', 24),
('C0516', 'Sneha Kapoor', 25, 'Uttar Pradesh', 'PAN', 'Rejected', 'High', 'Blurred Image', 28),
('C0517', 'Priya Singh', 47, 'Punjab', 'Passport', 'Pending', 'High', 'NA', 8),
('C0518', 'Rohit Jain', 35, 'Maharashtra', 'Aadhaar', 'Pending', 'Medium', 'NA', 12),
('C0519', 'Rohit Jain', 37, 'Gujarat', 'Aadhaar', 'Approved', 'Low', 'NA', 22),
('C0520', 'Amit Kumar', 50, 'Gujarat', 'Aadhaar', 'Approved', 'High', 'NA', 18),
('C0521', 'Arjun Verma', 28, 'Haryana', 'PAN', 'Pending', 'High', 'NA', 11),
('C0522', 'Arjun Verma', 62, 'Gujarat', 'PAN', 'Pending', 'Medium', 'NA', 19),
('C0523', 'Arjun Verma', 57, 'Punjab', 'Passport', 'Approved', 'High', 'NA', 17),
('C0524', 'Neha Gupta', 28, 'Rajasthan', 'PAN', 'Approved', 'Medium', 'NA', 25),
('C0525', 'Priya Singh', 29, 'Delhi', 'PAN', 'Approved', 'High', 'NA', 27),
('C0526', 'Amit Kumar', 43, 'Haryana', 'Aadhaar', 'Pending', 'Medium', 'NA', 6),
('C0527', 'Arjun Verma', 59, 'Gujarat', 'Passport', 'Pending', 'Medium', 'NA', 23),
('C0528', 'Arjun Verma', 41, 'Gujarat', 'Passport', 'Pending', 'Medium', 'NA', 6),
('C0529', 'Pooja Yadav', 58, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'Low', 'NA', 29),
('C0530', 'Neha Gupta', 38, 'Punjab', 'PAN', 'Rejected', 'Medium', 'Expired Document', 20),
('C0531', 'Pooja Yadav', 60, 'Punjab', 'PAN', 'Pending', 'High', 'NA', 8),
('C0532', 'Arjun Verma', 40, 'Rajasthan', 'PAN', 'Approved', 'High', 'NA', 8),
('C0533', 'Sneha Kapoor', 49, 'Delhi', 'PAN', 'Approved', 'High', 'NA', 6),
('C0534', 'Sneha Kapoor', 52, 'Delhi', 'PAN', 'Pending', 'Low', 'NA', 17),
('C0535', 'Arjun Verma', 58, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'High', 'NA', 9),
('C0536', 'Pooja Yadav', 54, 'Delhi', 'Passport', 'Pending', 'Low', 'NA', 13),
('C0537', 'Rahul Sharma', 42, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'High', 'NA', 25),
('C0538', 'Rohit Jain', 46, 'Punjab', 'Passport', 'Pending', 'Medium', 'NA', 11),
('C0539', 'Arjun Verma', 60, 'Karnataka', 'PAN', 'Rejected', 'High', 'Expired Document', 14),
('C0540', 'Arjun Verma', 38, 'Maharashtra', 'Aadhaar', 'Rejected', 'Medium', 'Invalid Address', 5),
('C0541', 'Pooja Yadav', 54, 'Rajasthan', 'Passport', 'Rejected', 'Medium', 'Invalid Address', 12),
('C0542', 'Neha Gupta', 28, 'Rajasthan', 'Passport', 'Pending', 'Low', 'NA', 26),
('C0543', 'Arjun Verma', 54, 'Rajasthan', 'Aadhaar', 'Pending', 'High', 'NA', 22),
('C0544', 'Neha Gupta', 31, 'Gujarat', 'Aadhaar', 'Rejected', 'High', 'Blurred Image', 16),
('C0545', 'Pooja Yadav', 56, 'Punjab', 'Passport', 'Approved', 'Medium', 'NA', 22),
('C0546', 'Sneha Kapoor', 56, 'Haryana', 'PAN', 'Pending', 'Low', 'NA', 30),
('C0547', 'Sneha Kapoor', 60, 'Karnataka', 'Aadhaar', 'Rejected', 'Medium', 'Blurred Image', 15),
('C0548', 'Rohit Jain', 58, 'Delhi', 'Aadhaar', 'Pending', 'Low', 'NA', 6),
('C0549', 'Amit Kumar', 42, 'Haryana', 'Aadhaar', 'Pending', 'Low', 'NA', 11),
('C0550', 'Neha Gupta', 33, 'Punjab', 'Aadhaar', 'Rejected', 'Low', 'Blurred Image', 13),
('C0551', 'Neha Gupta', 23, 'Karnataka', 'Aadhaar', 'Approved', 'High', 'NA', 11),
('C0552', 'Neha Gupta', 63, 'Haryana', 'Aadhaar', 'Approved', 'Low', 'NA', 22),
('C0553', 'Rohit Jain', 52, 'Karnataka', 'PAN', 'Pending', 'High', 'NA', 7),
('C0554', 'Priya Singh', 55, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'Low', 'NA', 29),
('C0555', 'Priya Singh', 53, 'Punjab', 'PAN', 'Approved', 'Low', 'NA', 14),
('C0556', 'Arjun Verma', 52, 'Maharashtra', 'Passport', 'Approved', 'Low', 'NA', 15),
('C0557', 'Sneha Kapoor', 33, 'Rajasthan', 'Aadhaar', 'Approved', 'Medium', 'NA', 28),
('C0558', 'Arjun Verma', 20, 'Gujarat', 'Aadhaar', 'Pending', 'High', 'NA', 14),
('C0559', 'Rohit Jain', 54, 'Rajasthan', 'PAN', 'Pending', 'Low', 'NA', 29),
('C0560', 'Arjun Verma', 32, 'Haryana', 'PAN', 'Pending', 'High', 'NA', 22),
('C0561', 'Rahul Sharma', 50, 'Delhi', 'Aadhaar', 'Approved', 'Low', 'NA', 10),
('C0562', 'Pooja Yadav', 44, 'Rajasthan', 'Passport', 'Pending', 'High', 'NA', 8),
('C0563', 'Priya Singh', 19, 'Punjab', 'Passport', 'Approved', 'High', 'NA', 19),
('C0564', 'Neha Gupta', 27, 'Delhi', 'PAN', 'Approved', 'Medium', 'NA', 20),
('C0565', 'Sneha Kapoor', 55, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 10),
('C0566', 'Rahul Sharma', 50, 'Haryana', 'Aadhaar', 'Rejected', 'Low', 'Missing Information', 17),
('C0567', 'Amit Kumar', 18, 'Delhi', 'Passport', 'Pending', 'Low', 'NA', 26),
('C0568', 'Amit Kumar', 61, 'Punjab', 'Passport', 'Pending', 'High', 'NA', 21),
('C0569', 'Arjun Verma', 36, 'Maharashtra', 'Aadhaar', 'Rejected', 'Low', 'Invalid Address', 9),
('C0570', 'Amit Kumar', 63, 'Delhi', 'Aadhaar', 'Pending', 'Low', 'NA', 12),
('C0571', 'Rahul Sharma', 25, 'Delhi', 'Passport', 'Pending', 'High', 'NA', 21),
('C0572', 'Neha Gupta', 57, 'Uttar Pradesh', 'Passport', 'Pending', 'High', 'NA', 20),
('C0573', 'Amit Kumar', 34, 'Gujarat', 'PAN', 'Approved', 'Medium', 'NA', 12),
('C0574', 'Rohit Jain', 44, 'Rajasthan', 'Passport', 'Rejected', 'Low', 'Invalid Address', 12),
('C0575', 'Neha Gupta', 51, 'Maharashtra', 'PAN', 'Pending', 'Medium', 'NA', 26),
('C0576', 'Priya Singh', 23, 'Haryana', 'Passport', 'Rejected', 'Medium', 'Expired Document', 20),
('C0577', 'Priya Singh', 39, 'Rajasthan', 'Passport', 'Rejected', 'High', 'Blurred Image', 23),
('C0578', 'Priya Singh', 54, 'Gujarat', 'PAN', 'Approved', 'Medium', 'NA', 19),
('C0579', 'Sneha Kapoor', 54, 'Rajasthan', 'Passport', 'Approved', 'Low', 'NA', 20),
('C0580', 'Amit Kumar', 42, 'Delhi', 'Aadhaar', 'Approved', 'High', 'NA', 25),
('C0581', 'Priya Singh', 63, 'Karnataka', 'PAN', 'Approved', 'Low', 'NA', 24),
('C0582', 'Rahul Sharma', 28, 'Punjab', 'Aadhaar', 'Pending', 'High', 'NA', 15),
('C0583', 'Rohit Jain', 32, 'Haryana', 'Passport', 'Rejected', 'Medium', 'Invalid Address', 24),
('C0584', 'Pooja Yadav', 40, 'Rajasthan', 'PAN', 'Rejected', 'Low', 'Blurred Image', 11),
('C0585', 'Rahul Sharma', 35, 'Gujarat', 'Passport', 'Approved', 'High', 'NA', 20),
('C0586', 'Neha Gupta', 53, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 27),
('C0587', 'Pooja Yadav', 22, 'Maharashtra', 'Aadhaar', 'Pending', 'High', 'NA', 16),
('C0588', 'Rahul Sharma', 33, 'Haryana', 'Passport', 'Rejected', 'Low', 'Invalid Address', 15),
('C0589', 'Rahul Sharma', 24, 'Maharashtra', 'Passport', 'Rejected', 'Low', 'Name Mismatch', 6),
('C0590', 'Priya Singh', 41, 'Haryana', 'Passport', 'Approved', 'Medium', 'NA', 9),
('C0591', 'Sneha Kapoor', 22, 'Gujarat', 'Passport', 'Approved', 'Low', 'NA', 15),
('C0592', 'Rahul Sharma', 59, 'Uttar Pradesh', 'PAN', 'Rejected', 'Low', 'Name Mismatch', 29),
('C0593', 'Arjun Verma', 50, 'Delhi', 'PAN', 'Pending', 'High', 'NA', 15),
('C0594', 'Rahul Sharma', 62, 'Haryana', 'PAN', 'Rejected', 'Low', 'Expired Document', 18),
('C0595', 'Amit Kumar', 41, 'Rajasthan', 'Passport', 'Rejected', 'Medium', 'Expired Document', 21),
('C0596', 'Sneha Kapoor', 60, 'Rajasthan', 'Passport', 'Approved', 'High', 'NA', 17),
('C0597', 'Rohit Jain', 39, 'Rajasthan', 'Aadhaar', 'Rejected', 'Low', 'Expired Document', 7),
('C0598', 'Rahul Sharma', 46, 'Maharashtra', 'PAN', 'Pending', 'Low', 'NA', 15),
('C0599', 'Arjun Verma', 63, 'Maharashtra', 'Aadhaar', 'Pending', 'Medium', 'NA', 24),
('C0600', 'Pooja Yadav', 30, 'Uttar Pradesh', 'PAN', 'Rejected', 'Medium', 'Name Mismatch', 8);

INSERT INTO KYC_Customers (Customer_ID, Customer_Name, Age, State, Document_Type, Verification_Status, Risk_Level, Rejection_Reason, Verification_Time_Minutes) VALUES
('C0601', 'Sneha Kapoor', 40, 'Punjab', 'PAN', 'Approved', 'Medium', 'NA', 14),
('C0602', 'Sneha Kapoor', 36, 'Karnataka', 'Passport', 'Approved', 'High', 'NA', 27),
('C0603', 'Rahul Sharma', 64, 'Delhi', 'Passport', 'Rejected', 'Low', 'Missing Information', 11),
('C0604', 'Priya Singh', 28, 'Haryana', 'Aadhaar', 'Rejected', 'High', 'Expired Document', 10),
('C0605', 'Amit Kumar', 20, 'Delhi', 'PAN', 'Approved', 'Medium', 'NA', 24),
('C0606', 'Neha Gupta', 64, 'Gujarat', 'PAN', 'Rejected', 'Medium', 'Expired Document', 27),
('C0607', 'Rohit Jain', 35, 'Delhi', 'Passport', 'Pending', 'Low', 'NA', 8),
('C0608', 'Amit Kumar', 57, 'Delhi', 'Aadhaar', 'Rejected', 'Low', 'Invalid Address', 11),
('C0609', 'Arjun Verma', 51, 'Haryana', 'Passport', 'Rejected', 'Medium', 'Invalid Address', 29),
('C0610', 'Neha Gupta', 27, 'Punjab', 'Passport', 'Approved', 'Low', 'NA', 6),
('C0611', 'Rahul Sharma', 50, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 23),
('C0612', 'Rahul Sharma', 39, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 29),
('C0613', 'Priya Singh', 29, 'Karnataka', 'Aadhaar', 'Rejected', 'Medium', 'Blurred Image', 14),
('C0614', 'Sneha Kapoor', 34, 'Punjab', 'PAN', 'Approved', 'Low', 'NA', 6),
('C0615', 'Priya Singh', 48, 'Maharashtra', 'Aadhaar', 'Pending', 'Medium', 'NA', 30),
('C0616', 'Pooja Yadav', 19, 'Rajasthan', 'Passport', 'Approved', 'Medium', 'NA', 13),
('C0617', 'Neha Gupta', 19, 'Gujarat', 'PAN', 'Rejected', 'Medium', 'Blurred Image', 12),
('C0618', 'Rahul Sharma', 21, 'Punjab', 'Aadhaar', 'Approved', 'Medium', 'NA', 26),
('C0619', 'Rohit Jain', 31, 'Maharashtra', 'Passport', 'Approved', 'High', 'NA', 19),
('C0620', 'Rahul Sharma', 52, 'Haryana', 'PAN', 'Rejected', 'High', 'Missing Information', 17),
('C0621', 'Rohit Jain', 24, 'Delhi', 'Aadhaar', 'Rejected', 'Medium', 'Blurred Image', 24),
('C0622', 'Amit Kumar', 35, 'Uttar Pradesh', 'Passport', 'Rejected', 'Medium', 'Name Mismatch', 8),
('C0623', 'Priya Singh', 18, 'Karnataka', 'Aadhaar', 'Approved', 'High', 'NA', 20),
('C0624', 'Rohit Jain', 32, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'High', 'Invalid Address', 23),
('C0625', 'Arjun Verma', 62, 'Rajasthan', 'Passport', 'Approved', 'High', 'NA', 6),
('C0626', 'Rohit Jain', 43, 'Delhi', 'Passport', 'Pending', 'Low', 'NA', 29),
('C0627', 'Pooja Yadav', 64, 'Maharashtra', 'Aadhaar', 'Pending', 'Medium', 'NA', 28),
('C0628', 'Priya Singh', 61, 'Karnataka', 'Passport', 'Approved', 'Low', 'NA', 7),
('C0629', 'Rahul Sharma', 58, 'Delhi', 'Passport', 'Rejected', 'Low', 'Name Mismatch', 13),
('C0630', 'Pooja Yadav', 28, 'Punjab', 'PAN', 'Rejected', 'Medium', 'Missing Information', 27),
('C0631', 'Rahul Sharma', 39, 'Haryana', 'Passport', 'Pending', 'Medium', 'NA', 28),
('C0632', 'Neha Gupta', 19, 'Punjab', 'PAN', 'Pending', 'Low', 'NA', 11),
('C0633', 'Neha Gupta', 32, 'Uttar Pradesh', 'PAN', 'Pending', 'Medium', 'NA', 8),
('C0634', 'Sneha Kapoor', 57, 'Haryana', 'Aadhaar', 'Rejected', 'Low', 'Missing Information', 12),
('C0635', 'Rahul Sharma', 31, 'Karnataka', 'Passport', 'Approved', 'High', 'NA', 6),
('C0636', 'Priya Singh', 61, 'Delhi', 'Aadhaar', 'Rejected', 'Low', 'Name Mismatch', 27),
('C0637', 'Neha Gupta', 58, 'Delhi', 'PAN', 'Approved', 'Medium', 'NA', 27),
('C0638', 'Neha Gupta', 47, 'Rajasthan', 'Passport', 'Pending', 'Medium', 'NA', 9),
('C0639', 'Pooja Yadav', 27, 'Maharashtra', 'Aadhaar', 'Pending', 'Medium', 'NA', 22),
('C0640', 'Arjun Verma', 50, 'Uttar Pradesh', 'PAN', 'Approved', 'High', 'NA', 30),
('C0641', 'Rahul Sharma', 38, 'Haryana', 'Aadhaar', 'Rejected', 'High', 'Name Mismatch', 10),
('C0642', 'Priya Singh', 65, 'Punjab', 'Passport', 'Approved', 'Medium', 'NA', 15),
('C0643', 'Amit Kumar', 47, 'Uttar Pradesh', 'Passport', 'Rejected', 'High', 'Missing Information', 30),
('C0644', 'Rahul Sharma', 61, 'Gujarat', 'Aadhaar', 'Pending', 'Low', 'NA', 14),
('C0645', 'Pooja Yadav', 23, 'Punjab', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 21),
('C0646', 'Neha Gupta', 41, 'Rajasthan', 'Passport', 'Pending', 'High', 'NA', 6),
('C0647', 'Rahul Sharma', 22, 'Uttar Pradesh', 'Passport', 'Rejected', 'High', 'Blurred Image', 19),
('C0648', 'Sneha Kapoor', 49, 'Gujarat', 'Aadhaar', 'Approved', 'High', 'NA', 22),
('C0649', 'Rahul Sharma', 23, 'Haryana', 'PAN', 'Approved', 'Medium', 'NA', 10),
('C0650', 'Arjun Verma', 23, 'Gujarat', 'PAN', 'Pending', 'Low', 'NA', 18),
('C0651', 'Pooja Yadav', 46, 'Punjab', 'Passport', 'Rejected', 'High', 'Missing Information', 29),
('C0652', 'Pooja Yadav', 29, 'Punjab', 'PAN', 'Pending', 'High', 'NA', 16),
('C0653', 'Amit Kumar', 40, 'Delhi', 'Aadhaar', 'Approved', 'Low', 'NA', 15),
('C0654', 'Pooja Yadav', 23, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'High', 'NA', 12),
('C0655', 'Arjun Verma', 19, 'Maharashtra', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 24),
('C0656', 'Neha Gupta', 37, 'Delhi', 'Passport', 'Pending', 'Medium', 'NA', 14),
('C0657', 'Arjun Verma', 28, 'Gujarat', 'Aadhaar', 'Rejected', 'Low', 'Invalid Address', 25),
('C0658', 'Priya Singh', 59, 'Karnataka', 'Aadhaar', 'Pending', 'Low', 'NA', 13),
('C0659', 'Sneha Kapoor', 25, 'Punjab', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 23),
('C0660', 'Rahul Sharma', 56, 'Uttar Pradesh', 'Passport', 'Pending', 'Low', 'NA', 22),
('C0661', 'Arjun Verma', 52, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'High', 'NA', 9),
('C0662', 'Sneha Kapoor', 44, 'Punjab', 'Aadhaar', 'Pending', 'High', 'NA', 11),
('C0663', 'Neha Gupta', 21, 'Uttar Pradesh', 'PAN', 'Approved', 'High', 'NA', 30),
('C0664', 'Priya Singh', 19, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'High', 'Blurred Image', 12),
('C0665', 'Rahul Sharma', 46, 'Rajasthan', 'Passport', 'Rejected', 'High', 'Blurred Image', 13),
('C0666', 'Rahul Sharma', 56, 'Maharashtra', 'Aadhaar', 'Pending', 'Medium', 'NA', 12),
('C0667', 'Neha Gupta', 63, 'Haryana', 'Passport', 'Rejected', 'Low', 'Expired Document', 24),
('C0668', 'Neha Gupta', 27, 'Punjab', 'PAN', 'Pending', 'Low', 'NA', 20),
('C0669', 'Arjun Verma', 21, 'Rajasthan', 'Passport', 'Approved', 'Medium', 'NA', 13),
('C0670', 'Sneha Kapoor', 46, 'Karnataka', 'PAN', 'Pending', 'Medium', 'NA', 11),
('C0671', 'Priya Singh', 38, 'Delhi', 'Passport', 'Rejected', 'Low', 'Name Mismatch', 26),
('C0672', 'Priya Singh', 54, 'Uttar Pradesh', 'PAN', 'Approved', 'Low', 'NA', 9),
('C0673', 'Rohit Jain', 52, 'Karnataka', 'Passport', 'Rejected', 'High', 'Name Mismatch', 21),
('C0674', 'Neha Gupta', 29, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Missing Information', 11),
('C0675', 'Neha Gupta', 19, 'Rajasthan', 'PAN', 'Pending', 'Low', 'NA', 21),
('C0676', 'Rohit Jain', 43, 'Punjab', 'Passport', 'Rejected', 'Low', 'Missing Information', 11),
('C0677', 'Neha Gupta', 55, 'Gujarat', 'PAN', 'Approved', 'Low', 'NA', 21),
('C0678', 'Rahul Sharma', 34, 'Punjab', 'Aadhaar', 'Approved', 'Low', 'NA', 10),
('C0679', 'Arjun Verma', 23, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 23),
('C0680', 'Rahul Sharma', 63, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Medium', 'Missing Information', 14),
('C0681', 'Pooja Yadav', 61, 'Delhi', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 28),
('C0682', 'Arjun Verma', 29, 'Karnataka', 'Passport', 'Pending', 'Medium', 'NA', 26),
('C0683', 'Pooja Yadav', 18, 'Punjab', 'Aadhaar', 'Rejected', 'Medium', 'Missing Information', 11),
('C0684', 'Rohit Jain', 58, 'Delhi', 'PAN', 'Rejected', 'Low', 'Missing Information', 10),
('C0685', 'Priya Singh', 58, 'Rajasthan', 'PAN', 'Rejected', 'High', 'Missing Information', 25),
('C0686', 'Sneha Kapoor', 36, 'Delhi', 'Passport', 'Rejected', 'High', 'Missing Information', 8),
('C0687', 'Amit Kumar', 64, 'Gujarat', 'Passport', 'Approved', 'High', 'NA', 24),
('C0688', 'Priya Singh', 54, 'Haryana', 'Passport', 'Approved', 'Medium', 'NA', 26),
('C0689', 'Arjun Verma', 19, 'Karnataka', 'Aadhaar', 'Rejected', 'Low', 'Invalid Address', 18),
('C0690', 'Priya Singh', 31, 'Delhi', 'Passport', 'Pending', 'Medium', 'NA', 22),
('C0691', 'Priya Singh', 32, 'Uttar Pradesh', 'Passport', 'Approved', 'Medium', 'NA', 26),
('C0692', 'Priya Singh', 62, 'Uttar Pradesh', 'Passport', 'Approved', 'Medium', 'NA', 24),
('C0693', 'Amit Kumar', 28, 'Punjab', 'PAN', 'Pending', 'Low', 'NA', 15),
('C0694', 'Priya Singh', 49, 'Haryana', 'PAN', 'Rejected', 'Low', 'Blurred Image', 19),
('C0695', 'Neha Gupta', 32, 'Maharashtra', 'PAN', 'Rejected', 'High', 'Missing Information', 23),
('C0696', 'Sneha Kapoor', 54, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'Medium', 'NA', 13),
('C0697', 'Pooja Yadav', 45, 'Maharashtra', 'Aadhaar', 'Approved', 'High', 'NA', 25),
('C0698', 'Sneha Kapoor', 46, 'Karnataka', 'Passport', 'Pending', 'Low', 'NA', 10),
('C0699', 'Neha Gupta', 22, 'Gujarat', 'Aadhaar', 'Pending', 'High', 'NA', 26),
('C0700', 'Neha Gupta', 36, 'Gujarat', 'Passport', 'Pending', 'High', 'NA', 15);

INSERT INTO KYC_Customers (Customer_ID, Customer_Name, Age, State, Document_Type, Verification_Status, Risk_Level, Rejection_Reason, Verification_Time_Minutes) VALUES
('C0701', 'Rahul Sharma', 42, 'Haryana', 'PAN', 'Approved', 'Medium', 'NA', 19),
('C0702', 'Neha Gupta', 29, 'Haryana', 'Passport', 'Pending', 'Medium', 'NA', 10),
('C0703', 'Neha Gupta', 18, 'Gujarat', 'Aadhaar', 'Approved', 'High', 'NA', 13),
('C0704', 'Rohit Jain', 45, 'Delhi', 'Aadhaar', 'Pending', 'Medium', 'NA', 20),
('C0705', 'Arjun Verma', 26, 'Delhi', 'Passport', 'Rejected', 'Low', 'Blurred Image', 9),
('C0706', 'Rahul Sharma', 54, 'Delhi', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 8),
('C0707', 'Arjun Verma', 38, 'Uttar Pradesh', 'PAN', 'Rejected', 'High', 'Name Mismatch', 19),
('C0708', 'Sneha Kapoor', 19, 'Haryana', 'PAN', 'Pending', 'Low', 'NA', 6),
('C0709', 'Priya Singh', 44, 'Maharashtra', 'Aadhaar', 'Rejected', 'High', 'Blurred Image', 25),
('C0710', 'Rahul Sharma', 54, 'Gujarat', 'Aadhaar', 'Approved', 'Medium', 'NA', 7),
('C0711', 'Pooja Yadav', 27, 'Punjab', 'PAN', 'Pending', 'Low', 'NA', 23),
('C0712', 'Neha Gupta', 19, 'Uttar Pradesh', 'Passport', 'Rejected', 'High', 'Invalid Address', 26),
('C0713', 'Arjun Verma', 26, 'Maharashtra', 'Passport', 'Rejected', 'High', 'Invalid Address', 6),
('C0714', 'Amit Kumar', 52, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 21),
('C0715', 'Rohit Jain', 44, 'Karnataka', 'Aadhaar', 'Pending', 'Low', 'NA', 11),
('C0716', 'Sneha Kapoor', 61, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 5),
('C0717', 'Rahul Sharma', 63, 'Delhi', 'Passport', 'Pending', 'Medium', 'NA', 13),
('C0718', 'Priya Singh', 50, 'Haryana', 'Passport', 'Approved', 'Low', 'NA', 10),
('C0719', 'Rohit Jain', 44, 'Punjab', 'Aadhaar', 'Approved', 'High', 'NA', 10),
('C0720', 'Neha Gupta', 61, 'Maharashtra', 'Passport', 'Pending', 'High', 'NA', 14),
('C0721', 'Sneha Kapoor', 64, 'Haryana', 'Passport', 'Approved', 'Low', 'NA', 24),
('C0722', 'Arjun Verma', 22, 'Uttar Pradesh', 'Passport', 'Rejected', 'Medium', 'Name Mismatch', 25),
('C0723', 'Arjun Verma', 55, 'Punjab', 'Aadhaar', 'Approved', 'Medium', 'NA', 7),
('C0724', 'Arjun Verma', 45, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 30),
('C0725', 'Sneha Kapoor', 65, 'Delhi', 'Aadhaar', 'Pending', 'High', 'NA', 10),
('C0726', 'Sneha Kapoor', 53, 'Delhi', 'Passport', 'Pending', 'Medium', 'NA', 14),
('C0727', 'Rohit Jain', 49, 'Karnataka', 'Aadhaar', 'Pending', 'Medium', 'NA', 6),
('C0728', 'Arjun Verma', 34, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 17),
('C0729', 'Pooja Yadav', 60, 'Delhi', 'Aadhaar', 'Pending', 'Low', 'NA', 6),
('C0730', 'Pooja Yadav', 37, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Medium', 'Expired Document', 21),
('C0731', 'Arjun Verma', 29, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'High', 'NA', 23),
('C0732', 'Amit Kumar', 27, 'Gujarat', 'Passport', 'Rejected', 'Medium', 'Expired Document', 11),
('C0733', 'Sneha Kapoor', 57, 'Haryana', 'PAN', 'Approved', 'Low', 'NA', 30),
('C0734', 'Arjun Verma', 28, 'Haryana', 'Passport', 'Pending', 'Medium', 'NA', 24),
('C0735', 'Priya Singh', 56, 'Uttar Pradesh', 'PAN', 'Pending', 'Low', 'NA', 28),
('C0736', 'Rohit Jain', 43, 'Delhi', 'Passport', 'Approved', 'Low', 'NA', 14),
('C0737', 'Pooja Yadav', 55, 'Karnataka', 'Aadhaar', 'Pending', 'High', 'NA', 5),
('C0738', 'Neha Gupta', 55, 'Rajasthan', 'Aadhaar', 'Approved', 'Low', 'NA', 24),
('C0739', 'Neha Gupta', 33, 'Punjab', 'PAN', 'Approved', 'Low', 'NA', 13),
('C0740', 'Amit Kumar', 37, 'Uttar Pradesh', 'PAN', 'Pending', 'High', 'NA', 6),
('C0741', 'Rohit Jain', 22, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 11),
('C0742', 'Arjun Verma', 26, 'Delhi', 'PAN', 'Pending', 'Low', 'NA', 5),
('C0743', 'Sneha Kapoor', 18, 'Rajasthan', 'Aadhaar', 'Pending', 'Low', 'NA', 23),
('C0744', 'Rohit Jain', 21, 'Haryana', 'Aadhaar', 'Rejected', 'Low', 'Expired Document', 26),
('C0745', 'Sneha Kapoor', 27, 'Rajasthan', 'PAN', 'Approved', 'High', 'NA', 28),
('C0746', 'Rohit Jain', 40, 'Karnataka', 'Aadhaar', 'Pending', 'Medium', 'NA', 22),
('C0747', 'Pooja Yadav', 22, 'Karnataka', 'Aadhaar', 'Rejected', 'Medium', 'Expired Document', 20),
('C0748', 'Priya Singh', 41, 'Haryana', 'Aadhaar', 'Rejected', 'Low', 'Missing Information', 19),
('C0749', 'Priya Singh', 48, 'Gujarat', 'Passport', 'Approved', 'Low', 'NA', 23),
('C0750', 'Priya Singh', 58, 'Punjab', 'Aadhaar', 'Pending', 'Medium', 'NA', 22),
('C0751', 'Pooja Yadav', 64, 'Punjab', 'Passport', 'Rejected', 'High', 'Missing Information', 14),
('C0752', 'Rohit Jain', 37, 'Karnataka', 'Aadhaar', 'Approved', 'High', 'NA', 16),
('C0753', 'Sneha Kapoor', 47, 'Punjab', 'Aadhaar', 'Rejected', 'High', 'Invalid Address', 11),
('C0754', 'Rahul Sharma', 24, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 8),
('C0755', 'Rohit Jain', 59, 'Gujarat', 'Passport', 'Rejected', 'Low', 'Missing Information', 25),
('C0756', 'Amit Kumar', 55, 'Rajasthan', 'PAN', 'Pending', 'Low', 'NA', 23),
('C0757', 'Rahul Sharma', 40, 'Punjab', 'Passport', 'Rejected', 'Low', 'Blurred Image', 22),
('C0758', 'Pooja Yadav', 22, 'Haryana', 'PAN', 'Pending', 'Medium', 'NA', 12),
('C0759', 'Priya Singh', 27, 'Karnataka', 'Passport', 'Approved', 'Low', 'NA', 28),
('C0760', 'Arjun Verma', 34, 'Uttar Pradesh', 'PAN', 'Rejected', 'Low', 'Blurred Image', 8),
('C0761', 'Amit Kumar', 53, 'Gujarat', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 18),
('C0762', 'Pooja Yadav', 23, 'Maharashtra', 'PAN', 'Rejected', 'High', 'Expired Document', 16),
('C0763', 'Neha Gupta', 46, 'Maharashtra', 'PAN', 'Rejected', 'High', 'Invalid Address', 5),
('C0764', 'Amit Kumar', 41, 'Maharashtra', 'PAN', 'Pending', 'High', 'NA', 30),
('C0765', 'Rohit Jain', 64, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'High', 'NA', 7),
('C0766', 'Priya Singh', 58, 'Uttar Pradesh', 'PAN', 'Approved', 'Low', 'NA', 23),
('C0767', 'Amit Kumar', 55, 'Delhi', 'PAN', 'Rejected', 'Medium', 'Expired Document', 23),
('C0768', 'Priya Singh', 54, 'Gujarat', 'Passport', 'Approved', 'Low', 'NA', 21),
('C0769', 'Rohit Jain', 31, 'Karnataka', 'PAN', 'Pending', 'Low', 'NA', 14),
('C0770', 'Priya Singh', 45, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 22),
('C0771', 'Pooja Yadav', 27, 'Haryana', 'Aadhaar', 'Pending', 'Low', 'NA', 20),
('C0772', 'Sneha Kapoor', 21, 'Maharashtra', 'Aadhaar', 'Rejected', 'Low', 'Invalid Address', 30),
('C0773', 'Priya Singh', 61, 'Rajasthan', 'Passport', 'Approved', 'High', 'NA', 21),
('C0774', 'Priya Singh', 47, 'Delhi', 'PAN', 'Rejected', 'High', 'Expired Document', 6),
('C0775', 'Pooja Yadav', 23, 'Delhi', 'Aadhaar', 'Rejected', 'High', 'Missing Information', 18),
('C0776', 'Amit Kumar', 62, 'Haryana', 'PAN', 'Approved', 'High', 'NA', 28),
('C0777', 'Neha Gupta', 22, 'Delhi', 'Aadhaar', 'Rejected', 'High', 'Name Mismatch', 16),
('C0778', 'Priya Singh', 28, 'Haryana', 'Passport', 'Rejected', 'Low', 'Name Mismatch', 6),
('C0779', 'Rahul Sharma', 50, 'Rajasthan', 'PAN', 'Pending', 'Low', 'NA', 10),
('C0780', 'Pooja Yadav', 33, 'Karnataka', 'Passport', 'Rejected', 'Low', 'Blurred Image', 20),
('C0781', 'Sneha Kapoor', 39, 'Punjab', 'Aadhaar', 'Rejected', 'High', 'Missing Information', 10),
('C0782', 'Rahul Sharma', 47, 'Delhi', 'Passport', 'Approved', 'Low', 'NA', 7),
('C0783', 'Sneha Kapoor', 29, 'Karnataka', 'Passport', 'Approved', 'High', 'NA', 27),
('C0784', 'Pooja Yadav', 40, 'Gujarat', 'PAN', 'Approved', 'Low', 'NA', 20),
('C0785', 'Amit Kumar', 61, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 23),
('C0786', 'Rahul Sharma', 18, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 7),
('C0787', 'Amit Kumar', 21, 'Rajasthan', 'Passport', 'Approved', 'Low', 'NA', 19),
('C0788', 'Rahul Sharma', 47, 'Gujarat', 'PAN', 'Pending', 'Medium', 'NA', 27),
('C0789', 'Amit Kumar', 18, 'Gujarat', 'Passport', 'Approved', 'High', 'NA', 24),
('C0790', 'Amit Kumar', 40, 'Maharashtra', 'Aadhaar', 'Approved', 'Medium', 'NA', 27),
('C0791', 'Pooja Yadav', 42, 'Maharashtra', 'Aadhaar', 'Approved', 'High', 'NA', 12),
('C0792', 'Neha Gupta', 65, 'Maharashtra', 'Aadhaar', 'Approved', 'Medium', 'NA', 18),
('C0793', 'Rahul Sharma', 52, 'Delhi', 'PAN', 'Approved', 'Medium', 'NA', 6),
('C0794', 'Priya Singh', 57, 'Delhi', 'Passport', 'Pending', 'Low', 'NA', 11),
('C0795', 'Pooja Yadav', 37, 'Gujarat', 'PAN', 'Pending', 'Medium', 'NA', 17),
('C0796', 'Arjun Verma', 41, 'Rajasthan', 'Aadhaar', 'Pending', 'High', 'NA', 23),
('C0797', 'Priya Singh', 22, 'Haryana', 'Aadhaar', 'Pending', 'High', 'NA', 13),
('C0798', 'Amit Kumar', 55, 'Haryana', 'Passport', 'Pending', 'Medium', 'NA', 9),
('C0799', 'Rohit Jain', 54, 'Uttar Pradesh', 'PAN', 'Pending', 'Medium', 'NA', 29),
('C0800', 'Neha Gupta', 23, 'Gujarat', 'PAN', 'Approved', 'Medium', 'NA', 23);

INSERT INTO KYC_Customers (Customer_ID, Customer_Name, Age, State, Document_Type, Verification_Status, Risk_Level, Rejection_Reason, Verification_Time_Minutes) VALUES
('C0801', 'Sneha Kapoor', 25, 'Haryana', 'Passport', 'Pending', 'Medium', 'NA', 22),
('C0802', 'Sneha Kapoor', 47, 'Punjab', 'Passport', 'Approved', 'High', 'NA', 26),
('C0803', 'Rohit Jain', 18, 'Haryana', 'PAN', 'Pending', 'Low', 'NA', 23),
('C0804', 'Rohit Jain', 64, 'Karnataka', 'Aadhaar', 'Rejected', 'Low', 'Name Mismatch', 27),
('C0805', 'Neha Gupta', 24, 'Gujarat', 'Aadhaar', 'Pending', 'Medium', 'NA', 11),
('C0806', 'Sneha Kapoor', 38, 'Karnataka', 'Aadhaar', 'Pending', 'Low', 'NA', 21),
('C0807', 'Amit Kumar', 30, 'Punjab', 'Aadhaar', 'Approved', 'Low', 'NA', 17),
('C0808', 'Pooja Yadav', 18, 'Haryana', 'PAN', 'Rejected', 'Low', 'Invalid Address', 30),
('C0809', 'Rohit Jain', 22, 'Delhi', 'Passport', 'Rejected', 'High', 'Blurred Image', 6),
('C0810', 'Arjun Verma', 51, 'Punjab', 'Passport', 'Approved', 'High', 'NA', 10),
('C0811', 'Priya Singh', 29, 'Uttar Pradesh', 'Passport', 'Pending', 'Medium', 'NA', 19),
('C0812', 'Priya Singh', 51, 'Gujarat', 'Aadhaar', 'Rejected', 'Medium', 'Blurred Image', 25),
('C0813', 'Rohit Jain', 19, 'Haryana', 'PAN', 'Rejected', 'Medium', 'Blurred Image', 21),
('C0814', 'Amit Kumar', 55, 'Maharashtra', 'Passport', 'Pending', 'Low', 'NA', 16),
('C0815', 'Rahul Sharma', 43, 'Punjab', 'Aadhaar', 'Pending', 'Medium', 'NA', 15),
('C0816', 'Arjun Verma', 64, 'Delhi', 'PAN', 'Approved', 'Medium', 'NA', 9),
('C0817', 'Priya Singh', 61, 'Gujarat', 'Passport', 'Approved', 'Low', 'NA', 8),
('C0818', 'Pooja Yadav', 55, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'Low', 'NA', 19),
('C0819', 'Rahul Sharma', 42, 'Karnataka', 'Aadhaar', 'Rejected', 'Medium', 'Name Mismatch', 23),
('C0820', 'Arjun Verma', 25, 'Maharashtra', 'PAN', 'Rejected', 'Low', 'Invalid Address', 21),
('C0821', 'Priya Singh', 34, 'Punjab', 'Passport', 'Approved', 'Medium', 'NA', 23),
('C0822', 'Pooja Yadav', 34, 'Maharashtra', 'Passport', 'Pending', 'High', 'NA', 5),
('C0823', 'Rohit Jain', 33, 'Delhi', 'Aadhaar', 'Approved', 'High', 'NA', 28),
('C0824', 'Pooja Yadav', 18, 'Rajasthan', 'Aadhaar', 'Pending', 'High', 'NA', 19),
('C0825', 'Neha Gupta', 62, 'Punjab', 'Passport', 'Approved', 'Medium', 'NA', 12),
('C0826', 'Neha Gupta', 35, 'Rajasthan', 'PAN', 'Pending', 'Low', 'NA', 9),
('C0827', 'Neha Gupta', 51, 'Delhi', 'Aadhaar', 'Approved', 'High', 'NA', 16),
('C0828', 'Arjun Verma', 55, 'Haryana', 'Aadhaar', 'Pending', 'High', 'NA', 12),
('C0829', 'Rahul Sharma', 27, 'Haryana', 'Passport', 'Pending', 'Low', 'NA', 17),
('C0830', 'Pooja Yadav', 56, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'High', 'NA', 22),
('C0831', 'Arjun Verma', 28, 'Karnataka', 'PAN', 'Rejected', 'Low', 'Expired Document', 29),
('C0832', 'Neha Gupta', 28, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 14),
('C0833', 'Sneha Kapoor', 31, 'Gujarat', 'PAN', 'Approved', 'High', 'NA', 30),
('C0834', 'Sneha Kapoor', 40, 'Delhi', 'Aadhaar', 'Approved', 'Low', 'NA', 15),
('C0835', 'Neha Gupta', 32, 'Karnataka', 'PAN', 'Rejected', 'Low', 'Invalid Address', 16),
('C0836', 'Priya Singh', 43, 'Punjab', 'Passport', 'Pending', 'High', 'NA', 12),
('C0837', 'Amit Kumar', 65, 'Punjab', 'Aadhaar', 'Approved', 'Medium', 'NA', 9),
('C0838', 'Neha Gupta', 59, 'Karnataka', 'Passport', 'Pending', 'High', 'NA', 21),
('C0839', 'Priya Singh', 58, 'Uttar Pradesh', 'Passport', 'Approved', 'High', 'NA', 20),
('C0840', 'Pooja Yadav', 43, 'Gujarat', 'Passport', 'Rejected', 'High', 'Missing Information', 23),
('C0841', 'Pooja Yadav', 55, 'Uttar Pradesh', 'PAN', 'Pending', 'Medium', 'NA', 10),
('C0842', 'Sneha Kapoor', 25, 'Uttar Pradesh', 'PAN', 'Pending', 'Medium', 'NA', 5),
('C0843', 'Neha Gupta', 60, 'Punjab', 'Passport', 'Rejected', 'Medium', 'Invalid Address', 10),
('C0844', 'Rahul Sharma', 27, 'Punjab', 'Passport', 'Approved', 'Medium', 'NA', 25),
('C0845', 'Sneha Kapoor', 46, 'Maharashtra', 'PAN', 'Rejected', 'High', 'Blurred Image', 24),
('C0846', 'Priya Singh', 54, 'Maharashtra', 'PAN', 'Pending', 'Medium', 'NA', 14),
('C0847', 'Rahul Sharma', 33, 'Delhi', 'PAN', 'Pending', 'High', 'NA', 24),
('C0848', 'Arjun Verma', 36, 'Haryana', 'Passport', 'Approved', 'Low', 'NA', 12),
('C0849', 'Rohit Jain', 19, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 21),
('C0850', 'Amit Kumar', 34, 'Delhi', 'PAN', 'Rejected', 'High', 'Missing Information', 13),
('C0851', 'Rohit Jain', 63, 'Punjab', 'Passport', 'Rejected', 'Medium', 'Name Mismatch', 24),
('C0852', 'Arjun Verma', 58, 'Rajasthan', 'PAN', 'Rejected', 'High', 'Blurred Image', 8),
('C0853', 'Arjun Verma', 58, 'Rajasthan', 'Aadhaar', 'Pending', 'Medium', 'NA', 25),
('C0854', 'Neha Gupta', 50, 'Gujarat', 'Aadhaar', 'Approved', 'Medium', 'NA', 8),
('C0855', 'Rohit Jain', 53, 'Gujarat', 'Passport', 'Pending', 'Medium', 'NA', 5),
('C0856', 'Rahul Sharma', 26, 'Maharashtra', 'Passport', 'Approved', 'Low', 'NA', 15),
('C0857', 'Priya Singh', 64, 'Maharashtra', 'Aadhaar', 'Rejected', 'Medium', 'Invalid Address', 23),
('C0858', 'Amit Kumar', 30, 'Maharashtra', 'PAN', 'Approved', 'High', 'NA', 9),
('C0859', 'Pooja Yadav', 24, 'Haryana', 'Passport', 'Pending', 'Medium', 'NA', 15),
('C0860', 'Neha Gupta', 54, 'Uttar Pradesh', 'PAN', 'Rejected', 'High', 'Expired Document', 15),
('C0861', 'Pooja Yadav', 48, 'Karnataka', 'Passport', 'Approved', 'Low', 'NA', 19),
('C0862', 'Rohit Jain', 39, 'Punjab', 'Passport', 'Pending', 'High', 'NA', 23),
('C0863', 'Pooja Yadav', 52, 'Haryana', 'PAN', 'Rejected', 'Medium', 'Missing Information', 13),
('C0864', 'Amit Kumar', 31, 'Maharashtra', 'Aadhaar', 'Rejected', 'High', 'Invalid Address', 28),
('C0865', 'Amit Kumar', 22, 'Uttar Pradesh', 'PAN', 'Pending', 'High', 'NA', 7),
('C0866', 'Rohit Jain', 21, 'Haryana', 'Passport', 'Rejected', 'High', 'Missing Information', 26),
('C0867', 'Pooja Yadav', 33, 'Gujarat', 'Passport', 'Rejected', 'Low', 'Blurred Image', 17),
('C0868', 'Pooja Yadav', 40, 'Rajasthan', 'Aadhaar', 'Pending', 'High', 'NA', 6),
('C0869', 'Pooja Yadav', 34, 'Punjab', 'Passport', 'Pending', 'High', 'NA', 23),
('C0870', 'Arjun Verma', 61, 'Uttar Pradesh', 'PAN', 'Approved', 'Low', 'NA', 29),
('C0871', 'Priya Singh', 55, 'Gujarat', 'PAN', 'Approved', 'Medium', 'NA', 6),
('C0872', 'Rohit Jain', 25, 'Karnataka', 'Passport', 'Approved', 'High', 'NA', 24),
('C0873', 'Rahul Sharma', 64, 'Delhi', 'Aadhaar', 'Rejected', 'Medium', 'Blurred Image', 7),
('C0874', 'Pooja Yadav', 31, 'Karnataka', 'Aadhaar', 'Rejected', 'Low', 'Name Mismatch', 14),
('C0875', 'Rahul Sharma', 33, 'Rajasthan', 'Passport', 'Pending', 'Low', 'NA', 8),
('C0876', 'Sneha Kapoor', 54, 'Punjab', 'PAN', 'Approved', 'High', 'NA', 12),
('C0877', 'Neha Gupta', 48, 'Gujarat', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 10),
('C0878', 'Rohit Jain', 60, 'Karnataka', 'Passport', 'Approved', 'Medium', 'NA', 17),
('C0879', 'Amit Kumar', 54, 'Delhi', 'Passport', 'Approved', 'Medium', 'NA', 30),
('C0880', 'Rahul Sharma', 31, 'Rajasthan', 'Passport', 'Pending', 'Low', 'NA', 5),
('C0881', 'Amit Kumar', 56, 'Punjab', 'Aadhaar', 'Rejected', 'Medium', 'Expired Document', 6),
('C0882', 'Rohit Jain', 59, 'Rajasthan', 'Passport', 'Approved', 'High', 'NA', 13),
('C0883', 'Sneha Kapoor', 47, 'Gujarat', 'Passport', 'Rejected', 'Medium', 'Missing Information', 29),
('C0884', 'Sneha Kapoor', 53, 'Maharashtra', 'PAN', 'Rejected', 'Medium', 'Expired Document', 18),
('C0885', 'Arjun Verma', 44, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'High', 'NA', 29),
('C0886', 'Rohit Jain', 51, 'Karnataka', 'Passport', 'Pending', 'Medium', 'NA', 8),
('C0887', 'Rohit Jain', 48, 'Haryana', 'Aadhaar', 'Approved', 'Medium', 'NA', 10),
('C0888', 'Rahul Sharma', 51, 'Gujarat', 'PAN', 'Pending', 'Low', 'NA', 11),
('C0889', 'Neha Gupta', 54, 'Haryana', 'Aadhaar', 'Pending', 'High', 'NA', 27),
('C0890', 'Neha Gupta', 35, 'Punjab', 'Aadhaar', 'Pending', 'Medium', 'NA', 19),
('C0891', 'Neha Gupta', 46, 'Rajasthan', 'Passport', 'Rejected', 'Low', 'Invalid Address', 23),
('C0892', 'Rahul Sharma', 53, 'Haryana', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 14),
('C0893', 'Pooja Yadav', 44, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'High', 'Missing Information', 11),
('C0894', 'Rahul Sharma', 37, 'Maharashtra', 'Passport', 'Rejected', 'Medium', 'Missing Information', 9),
('C0895', 'Arjun Verma', 62, 'Delhi', 'Passport', 'Approved', 'Low', 'NA', 6),
('C0896', 'Priya Singh', 62, 'Punjab', 'Passport', 'Pending', 'High', 'NA', 21),
('C0897', 'Pooja Yadav', 50, 'Uttar Pradesh', 'PAN', 'Pending', 'Medium', 'NA', 15),
('C0898', 'Neha Gupta', 56, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 18),
('C0899', 'Amit Kumar', 36, 'Gujarat', 'Aadhaar', 'Pending', 'High', 'NA', 25),
('C0900', 'Arjun Verma', 42, 'Rajasthan', 'Passport', 'Rejected', 'High', 'Name Mismatch', 21);

INSERT INTO KYC_Customers (Customer_ID, Customer_Name, Age, State, Document_Type, Verification_Status, Risk_Level, Rejection_Reason, Verification_Time_Minutes) VALUES
('C0901', 'Arjun Verma', 65, 'Uttar Pradesh', 'PAN', 'Rejected', 'Low', 'Invalid Address', 28),
('C0902', 'Arjun Verma', 32, 'Karnataka', 'Aadhaar', 'Pending', 'Low', 'NA', 20),
('C0903', 'Amit Kumar', 59, 'Delhi', 'Aadhaar', 'Approved', 'Medium', 'NA', 28),
('C0904', 'Rahul Sharma', 23, 'Haryana', 'Passport', 'Pending', 'High', 'NA', 25),
('C0905', 'Pooja Yadav', 33, 'Karnataka', 'PAN', 'Pending', 'Low', 'NA', 18),
('C0906', 'Rahul Sharma', 24, 'Rajasthan', 'PAN', 'Pending', 'Low', 'NA', 22),
('C0907', 'Neha Gupta', 45, 'Gujarat', 'Aadhaar', 'Approved', 'Low', 'NA', 30),
('C0908', 'Neha Gupta', 24, 'Delhi', 'Aadhaar', 'Pending', 'Medium', 'NA', 17),
('C0909', 'Arjun Verma', 30, 'Gujarat', 'Passport', 'Pending', 'Low', 'NA', 23),
('C0910', 'Priya Singh', 46, 'Karnataka', 'Passport', 'Rejected', 'High', 'Missing Information', 27),
('C0911', 'Priya Singh', 31, 'Uttar Pradesh', 'PAN', 'Approved', 'High', 'NA', 29),
('C0912', 'Rahul Sharma', 43, 'Delhi', 'Passport', 'Approved', 'Low', 'NA', 18),
('C0913', 'Sneha Kapoor', 65, 'Rajasthan', 'Aadhaar', 'Pending', 'Medium', 'NA', 27),
('C0914', 'Rahul Sharma', 30, 'Maharashtra', 'PAN', 'Approved', 'High', 'NA', 26),
('C0915', 'Pooja Yadav', 34, 'Rajasthan', 'PAN', 'Rejected', 'Low', 'Blurred Image', 28),
('C0916', 'Priya Singh', 25, 'Maharashtra', 'PAN', 'Pending', 'Medium', 'NA', 10),
('C0917', 'Rohit Jain', 55, 'Delhi', 'Aadhaar', 'Rejected', 'Low', 'Expired Document', 30),
('C0918', 'Arjun Verma', 33, 'Karnataka', 'Aadhaar', 'Rejected', 'Medium', 'Invalid Address', 17),
('C0919', 'Neha Gupta', 27, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Name Mismatch', 5),
('C0920', 'Priya Singh', 48, 'Uttar Pradesh', 'PAN', 'Approved', 'Medium', 'NA', 13),
('C0921', 'Sneha Kapoor', 23, 'Punjab', 'Aadhaar', 'Rejected', 'Low', 'Blurred Image', 13),
('C0922', 'Rahul Sharma', 29, 'Uttar Pradesh', 'PAN', 'Rejected', 'Low', 'Missing Information', 5),
('C0923', 'Sneha Kapoor', 22, 'Delhi', 'Passport', 'Pending', 'Medium', 'NA', 6),
('C0924', 'Neha Gupta', 31, 'Karnataka', 'PAN', 'Pending', 'Medium', 'NA', 30),
('C0925', 'Pooja Yadav', 18, 'Punjab', 'PAN', 'Pending', 'High', 'NA', 28),
('C0926', 'Rohit Jain', 30, 'Punjab', 'PAN', 'Approved', 'High', 'NA', 18),
('C0927', 'Pooja Yadav', 34, 'Haryana', 'Aadhaar', 'Rejected', 'High', 'Expired Document', 24),
('C0928', 'Priya Singh', 19, 'Maharashtra', 'Aadhaar', 'Approved', 'Medium', 'NA', 15),
('C0929', 'Rohit Jain', 21, 'Uttar Pradesh', 'PAN', 'Approved', 'Medium', 'NA', 30),
('C0930', 'Rohit Jain', 47, 'Haryana', 'Passport', 'Rejected', 'Medium', 'Expired Document', 16),
('C0931', 'Rahul Sharma', 30, 'Maharashtra', 'PAN', 'Pending', 'Medium', 'NA', 29),
('C0932', 'Arjun Verma', 22, 'Haryana', 'PAN', 'Rejected', 'Medium', 'Invalid Address', 23),
('C0933', 'Priya Singh', 24, 'Haryana', 'Passport', 'Rejected', 'Medium', 'Name Mismatch', 20),
('C0934', 'Neha Gupta', 43, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Invalid Address', 30),
('C0935', 'Amit Kumar', 49, 'Uttar Pradesh', 'Aadhaar', 'Pending', 'High', 'NA', 11),
('C0936', 'Amit Kumar', 40, 'Rajasthan', 'Passport', 'Approved', 'Medium', 'NA', 7),
('C0937', 'Rahul Sharma', 45, 'Haryana', 'PAN', 'Pending', 'Low', 'NA', 6),
('C0938', 'Priya Singh', 23, 'Karnataka', 'PAN', 'Approved', 'High', 'NA', 14),
('C0939', 'Sneha Kapoor', 29, 'Delhi', 'PAN', 'Rejected', 'High', 'Blurred Image', 15),
('C0940', 'Pooja Yadav', 32, 'Gujarat', 'Aadhaar', 'Pending', 'High', 'NA', 30),
('C0941', 'Sneha Kapoor', 28, 'Maharashtra', 'Aadhaar', 'Rejected', 'High', 'Blurred Image', 9),
('C0942', 'Priya Singh', 18, 'Haryana', 'PAN', 'Approved', 'Low', 'NA', 30),
('C0943', 'Sneha Kapoor', 28, 'Rajasthan', 'Passport', 'Pending', 'High', 'NA', 21),
('C0944', 'Amit Kumar', 41, 'Rajasthan', 'PAN', 'Rejected', 'Medium', 'Name Mismatch', 16),
('C0945', 'Arjun Verma', 43, 'Punjab', 'PAN', 'Pending', 'High', 'NA', 9),
('C0946', 'Neha Gupta', 65, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Low', 'Invalid Address', 10),
('C0947', 'Neha Gupta', 57, 'Rajasthan', 'Aadhaar', 'Rejected', 'Low', 'Blurred Image', 8),
('C0948', 'Arjun Verma', 50, 'Delhi', 'Aadhaar', 'Approved', 'High', 'NA', 11),
('C0949', 'Sneha Kapoor', 38, 'Maharashtra', 'Aadhaar', 'Approved', 'Low', 'NA', 22),
('C0950', 'Amit Kumar', 20, 'Haryana', 'Passport', 'Pending', 'High', 'NA', 21),
('C0951', 'Neha Gupta', 46, 'Delhi', 'Passport', 'Approved', 'High', 'NA', 6),
('C0952', 'Arjun Verma', 37, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Medium', 'Blurred Image', 8),
('C0953', 'Rohit Jain', 60, 'Delhi', 'PAN', 'Approved', 'Low', 'NA', 14),
('C0954', 'Arjun Verma', 46, 'Uttar Pradesh', 'Aadhaar', 'Rejected', 'Low', 'Invalid Address', 17),
('C0955', 'Pooja Yadav', 47, 'Haryana', 'PAN', 'Rejected', 'Low', 'Name Mismatch', 27),
('C0956', 'Rohit Jain', 35, 'Gujarat', 'Aadhaar', 'Pending', 'Low', 'NA', 16),
('C0957', 'Rahul Sharma', 18, 'Rajasthan', 'PAN', 'Pending', 'High', 'NA', 15),
('C0958', 'Pooja Yadav', 36, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 6),
('C0959', 'Pooja Yadav', 50, 'Gujarat', 'PAN', 'Rejected', 'Low', 'Invalid Address', 6),
('C0960', 'Priya Singh', 42, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Missing Information', 18),
('C0961', 'Rohit Jain', 32, 'Maharashtra', 'Passport', 'Pending', 'Low', 'NA', 15),
('C0962', 'Arjun Verma', 60, 'Delhi', 'PAN', 'Approved', 'Low', 'NA', 21),
('C0963', 'Neha Gupta', 39, 'Delhi', 'Passport', 'Rejected', 'Low', 'Missing Information', 23),
('C0964', 'Priya Singh', 62, 'Delhi', 'Passport', 'Pending', 'Low', 'NA', 8),
('C0965', 'Pooja Yadav', 40, 'Punjab', 'Passport', 'Pending', 'High', 'NA', 5),
('C0966', 'Arjun Verma', 59, 'Rajasthan', 'Aadhaar', 'Pending', 'Low', 'NA', 5),
('C0967', 'Pooja Yadav', 36, 'Karnataka', 'Aadhaar', 'Rejected', 'Medium', 'Invalid Address', 26),
('C0968', 'Priya Singh', 57, 'Haryana', 'Aadhaar', 'Approved', 'Medium', 'NA', 10),
('C0969', 'Rahul Sharma', 47, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Blurred Image', 12),
('C0970', 'Neha Gupta', 60, 'Uttar Pradesh', 'PAN', 'Pending', 'Low', 'NA', 27),
('C0971', 'Pooja Yadav', 46, 'Haryana', 'PAN', 'Pending', 'Low', 'NA', 28),
('C0972', 'Arjun Verma', 60, 'Delhi', 'Aadhaar', 'Pending', 'Medium', 'NA', 10),
('C0973', 'Rohit Jain', 63, 'Gujarat', 'Aadhaar', 'Pending', 'Medium', 'NA', 25),
('C0974', 'Rahul Sharma', 60, 'Rajasthan', 'Aadhaar', 'Pending', 'Low', 'NA', 18),
('C0975', 'Amit Kumar', 46, 'Karnataka', 'PAN', 'Pending', 'High', 'NA', 13),
('C0976', 'Rahul Sharma', 24, 'Punjab', 'PAN', 'Pending', 'High', 'NA', 26),
('C0977', 'Pooja Yadav', 43, 'Gujarat', 'Aadhaar', 'Rejected', 'High', 'Blurred Image', 29),
('C0978', 'Pooja Yadav', 50, 'Rajasthan', 'PAN', 'Rejected', 'Medium', 'Missing Information', 30),
('C0979', 'Priya Singh', 37, 'Maharashtra', 'PAN', 'Approved', 'Medium', 'NA', 16),
('C0980', 'Pooja Yadav', 43, 'Gujarat', 'PAN', 'Rejected', 'Low', 'Blurred Image', 30),
('C0981', 'Rahul Sharma', 59, 'Rajasthan', 'Passport', 'Approved', 'High', 'NA', 21),
('C0982', 'Arjun Verma', 20, 'Gujarat', 'Passport', 'Approved', 'Medium', 'NA', 13),
('C0983', 'Neha Gupta', 43, 'Maharashtra', 'PAN', 'Approved', 'Medium', 'NA', 30),
('C0984', 'Sneha Kapoor', 60, 'Karnataka', 'PAN', 'Rejected', 'High', 'Name Mismatch', 23),
('C0985', 'Pooja Yadav', 26, 'Punjab', 'PAN', 'Pending', 'Medium', 'NA', 26),
('C0986', 'Arjun Verma', 55, 'Karnataka', 'Passport', 'Rejected', 'High', 'Name Mismatch', 21),
('C0987', 'Pooja Yadav', 52, 'Gujarat', 'Aadhaar', 'Pending', 'High', 'NA', 5),
('C0988', 'Priya Singh', 32, 'Maharashtra', 'PAN', 'Rejected', 'High', 'Blurred Image', 5),
('C0989', 'Rahul Sharma', 50, 'Uttar Pradesh', 'Aadhaar', 'Approved', 'Medium', 'NA', 26),
('C0990', 'Pooja Yadav', 30, 'Rajasthan', 'PAN', 'Pending', 'Medium', 'NA', 19),
('C0991', 'Pooja Yadav', 61, 'Rajasthan', 'Passport', 'Pending', 'Low', 'NA', 28),
('C0992', 'Neha Gupta', 43, 'Punjab', 'PAN', 'Pending', 'High', 'NA', 22),
('C0993', 'Arjun Verma', 65, 'Delhi', 'Aadhaar', 'Pending', 'High', 'NA', 29),
('C0994', 'Rahul Sharma', 57, 'Rajasthan', 'Aadhaar', 'Approved', 'Medium', 'NA', 7),
('C0995', 'Neha Gupta', 59, 'Uttar Pradesh', 'Passport', 'Rejected', 'Low', 'Name Mismatch', 19),
('C0996', 'Rahul Sharma', 64, 'Delhi', 'PAN', 'Pending', 'Medium', 'NA', 8),
('C0997', 'Sneha Kapoor', 57, 'Uttar Pradesh', 'PAN', 'Pending', 'High', 'NA', 17),
('C0998', 'Rohit Jain', 58, 'Rajasthan', 'PAN', 'Approved', 'Low', 'NA', 5),
('C0999', 'Rohit Jain', 23, 'Gujarat', 'Aadhaar', 'Approved', 'Medium', 'NA', 15),
('C1000', 'Rohit Jain', 57, 'Maharashtra', 'PAN', 'Approved', 'Medium', 'NA', 6);



-- KPI 1: Total Customers
-- What it shows: Total number of customers in the dataset
-- ─────────────────────────────────────────────────────────────
SELECT COUNT(*) AS Total_Customers
FROM KYC_Customers;


-- KPI 2: Verification Status Breakdown (Approved / Rejected / Pending)
-- What it shows: How many customers are in each status
-- ─────────────────────────────────────────────────────────────
SELECT
    Verification_Status,
    COUNT(*) AS Total
FROM KYC_Customers
GROUP BY Verification_Status
ORDER BY Total DESC;


-- KPI 3: Approval Rate %
-- What it shows: What percentage of customers got approved
-- ─────────────────────────────────────────────────────────────
SELECT
    ROUND(
        SUM(CASE WHEN Verification_Status = 'Approved' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*), 2
    ) AS Approval_Rate_Pct
FROM KYC_Customers;


-- KPI 4: Risk Level Distribution
-- What it shows: How many customers fall under Low / Medium / High risk
-- ─────────────────────────────────────────────────────────────
SELECT
    Risk_Level,
    COUNT(*) AS Total_Customers
FROM KYC_Customers
GROUP BY Risk_Level
ORDER BY Total_Customers DESC;


-- KPI 5: Top Rejection Reasons
-- What it shows: Why are customers getting rejected?
-- ─────────────────────────────────────────────────────────────
SELECT
    Rejection_Reason,
    COUNT(*) AS Total
FROM KYC_Customers
WHERE Verification_Status = 'Rejected'
  AND Rejection_Reason != 'NA'
GROUP BY Rejection_Reason
ORDER BY Total DESC;


-- KPI 6: Document Type Performance
-- What it shows: Which document type is used most and has highest rejection
-- ─────────────────────────────────────────────────────────────
SELECT
    Document_Type,
    COUNT(*) AS Total_Verifications,
    SUM(CASE WHEN Verification_Status = 'Approved' THEN 1 ELSE 0 END) AS Approved,
    SUM(CASE WHEN Verification_Status = 'Rejected' THEN 1 ELSE 0 END) AS Rejected,
    ROUND(
        SUM(CASE WHEN Verification_Status = 'Approved' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*), 2
    ) AS Approval_Rate_Pct
FROM KYC_Customers
GROUP BY Document_Type
ORDER BY Total_Verifications DESC;


-- KPI 7: Average Verification Time
-- What it shows: How long does KYC verification take on average
-- ─────────────────────────────────────────────────────────────
SELECT
    ROUND(AVG(Verification_Time_Minutes), 2) AS Avg_Verification_Time
FROM KYC_Customers;


-- KPI 8: State-wise KYC Summary
-- What it shows: Approved, Rejected, Pending count per state
-- ─────────────────────────────────────────────────────────────
SELECT
    State,
    SUM(CASE WHEN Verification_Status = 'Approved' THEN 1 ELSE 0 END) AS Approved,
    SUM(CASE WHEN Verification_Status = 'Rejected' THEN 1 ELSE 0 END) AS Rejected,
    SUM(CASE WHEN Verification_Status = 'Pending'  THEN 1 ELSE 0 END) AS Pending,
    COUNT(*) AS Total
FROM KYC_Customers
GROUP BY State
ORDER BY Total DESC;
